export interface GlossaryTerm {
  term: string;
  reading?: string;
  category: string;
  description: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // 基礎
  {
    term: "puts",
    reading: "ぷっつ",
    category: "基礎",
    description: "改行付きで標準出力に出力するメソッド",
  },
  {
    term: "print",
    reading: "ぷりんと",
    category: "基礎",
    description: "改行なしで標準出力に出力するメソッド",
  },
  {
    term: "p",
    reading: "ぴー",
    category: "基礎",
    description: "デバッグ用出力。inspect結果を表示する",
  },
  {
    term: "irb",
    reading: "あいあーるびー",
    category: "基礎",
    description: "Interactive Ruby。対話型Ruby実行環境",
  },
  {
    term: "nil",
    reading: "にる",
    category: "基礎",
    description: "「何もない」を表すオブジェクト。NilClassの唯一のインスタンス",
  },
  {
    term: "true/false",
    reading: "とぅるー/ふぉるす",
    category: "基礎",
    description: "真偽値を表すオブジェクト",
  },
  {
    term: "Symbol",
    reading: "しんぼる",
    category: "基礎",
    description: "イミュータブルな識別子。:nameのようにコロンで始まる",
  },
  {
    term: "String",
    reading: "すとりんぐ",
    category: "基礎",
    description: "文字列クラス。ミュータブルでエンコーディング情報を持つ",
  },
  {
    term: "Integer",
    reading: "いんてじゃー",
    category: "基礎",
    description: "整数クラス。Rubyでは任意精度の整数をサポート",
  },
  {
    term: "Float",
    reading: "ふろーと",
    category: "基礎",
    description: "浮動小数点数クラス。IEEE 754倍精度",
  },
  {
    term: "Array",
    reading: "あれい",
    category: "基礎",
    description: "順序付きコレクション。異なる型の要素を格納可能",
  },
  {
    term: "Hash",
    reading: "はっしゅ",
    category: "基礎",
    description: "キーと値のペアを格納する連想配列",
  },
  {
    term: "Range",
    reading: "れんじ",
    category: "基礎",
    description: "範囲オブジェクト。(1..10)や(1...10)で作成",
  },
  {
    term: "Regexp",
    reading: "れぐえくすぷ",
    category: "基礎",
    description: "正規表現クラス。/pattern/リテラルで作成",
  },
  {
    term: "frozen",
    reading: "ふろーずん",
    category: "基礎",
    description: "オブジェクトを変更不可にするメソッド。freeze/frozen?",
  },
  {
    term: "変数",
    reading: "へんすう",
    category: "基礎",
    description: "ローカル変数(小文字)、インスタンス変数(@)、クラス変数(@@)、グローバル変数($)",
  },
  {
    term: "定数",
    reading: "ていすう",
    category: "基礎",
    description: "大文字で始まる識別子。再代入すると警告",
  },
  {
    term: "式展開",
    reading: "しきてんかい",
    category: "基礎",
    description: "ダブルクォート文字列内で#{式}として値を埋め込む機能",
  },
  {
    term: "ヒアドキュメント",
    reading: "ひあどきゅめんと",
    category: "基礎",
    description: "<<~EOS...EOSで複数行文字列を記述する構文",
  },
  {
    term: "三項演算子",
    reading: "さんこうえんざんし",
    category: "基礎",
    description: "condition ? true_value : false_value の条件式",
  },

  // クラス・オブジェクト
  {
    term: "class",
    reading: "くらす",
    category: "クラス・オブジェクト",
    description: "クラスを定義するキーワード",
  },
  {
    term: "new",
    reading: "にゅー",
    category: "クラス・オブジェクト",
    description: "クラスからインスタンスを生成するメソッド",
  },
  {
    term: "initialize",
    reading: "いにしゃらいず",
    category: "クラス・オブジェクト",
    description: "コンストラクタ。newで自動的に呼ばれる",
  },
  {
    term: "self",
    reading: "せるふ",
    category: "クラス・オブジェクト",
    description: "現在のオブジェクトへの参照",
  },
  {
    term: "attr_accessor",
    reading: "あとりびゅーと あくせさー",
    category: "クラス・オブジェクト",
    description: "ゲッターとセッターを同時に定義するマクロ",
  },
  {
    term: "attr_reader",
    reading: "あとりびゅーと りーだー",
    category: "クラス・オブジェクト",
    description: "ゲッターのみを定義するマクロ",
  },
  {
    term: "attr_writer",
    reading: "あとりびゅーと らいたー",
    category: "クラス・オブジェクト",
    description: "セッターのみを定義するマクロ",
  },
  {
    term: "インスタンス変数",
    reading: "いんすたんすへんすう",
    category: "クラス・オブジェクト",
    description: "@で始まる変数。各インスタンスに固有",
  },
  {
    term: "クラス変数",
    reading: "くらすへんすう",
    category: "クラス・オブジェクト",
    description: "@@で始まる変数。クラスとサブクラスで共有",
  },
  {
    term: "継承",
    reading: "けいしょう",
    category: "クラス・オブジェクト",
    description: "class Child < Parentで親クラスの機能を引き継ぐ",
  },
  {
    term: "super",
    reading: "すーぱー",
    category: "クラス・オブジェクト",
    description: "親クラスの同名メソッドを呼び出す",
  },
  {
    term: "オーバーライド",
    reading: "おーばーらいど",
    category: "クラス・オブジェクト",
    description: "親クラスのメソッドを子クラスで再定義すること",
  },
  {
    term: "ダックタイピング",
    reading: "だっくたいぴんぐ",
    category: "クラス・オブジェクト",
    description: "オブジェクトの型より振る舞い（メソッド）を重視する考え方",
  },
  {
    term: "オープンクラス",
    reading: "おーぷんくらす",
    category: "クラス・オブジェクト",
    description: "既存のクラスにメソッドを後から追加できるRubyの特徴",
  },
  {
    term: "BasicObject",
    reading: "べーしっくおぶじぇくと",
    category: "クラス・オブジェクト",
    description: "すべてのクラスの最上位クラス",
  },
  {
    term: "Object",
    reading: "おぶじぇくと",
    category: "クラス・オブジェクト",
    description: "ほとんどのクラスの親クラス。Kernelモジュールをinclude",
  },
  {
    term: "Kernel",
    reading: "かーねる",
    category: "クラス・オブジェクト",
    description: "puts・require等の基本メソッドを提供するモジュール",
  },
  {
    term: "respond_to?",
    reading: "りすぽんどとぅ",
    category: "クラス・オブジェクト",
    description: "オブジェクトが特定のメソッドに応答できるか確認",
  },
  {
    term: "send",
    reading: "せんど",
    category: "クラス・オブジェクト",
    description: "メソッド名を動的に指定して呼び出す",
  },
  {
    term: "method_missing",
    reading: "めそっどみっしんぐ",
    category: "クラス・オブジェクト",
    description: "存在しないメソッド呼び出し時に実行されるフック",
  },

  // ブロック・イテレータ
  {
    term: "block",
    reading: "ぶろっく",
    category: "ブロック・イテレータ",
    description: "メソッドに渡すコードの塊。do...endまたは{}で記述",
  },
  {
    term: "yield",
    reading: "いーるど",
    category: "ブロック・イテレータ",
    description: "メソッド内でブロックを実行するキーワード",
  },
  {
    term: "Proc",
    reading: "ぷろっく",
    category: "ブロック・イテレータ",
    description: "ブロックをオブジェクト化したもの。Proc.newで作成",
  },
  {
    term: "Lambda",
    reading: "らむだ",
    category: "ブロック・イテレータ",
    description: "Procの一種。引数チェックが厳密でreturnが異なる",
  },
  {
    term: "クロージャ",
    reading: "くろーじゃ",
    category: "ブロック・イテレータ",
    description: "外部の変数をキャプチャするブロック・Proc・Lambda",
  },
  {
    term: "each",
    reading: "いーち",
    category: "ブロック・イテレータ",
    description: "コレクションの各要素に対してブロックを実行するイテレータ",
  },
  {
    term: "map",
    reading: "まっぷ",
    category: "ブロック・イテレータ",
    description: "各要素を変換して新しい配列を返すメソッド。collectとも呼ばれる",
  },
  {
    term: "select",
    reading: "せれくと",
    category: "ブロック・イテレータ",
    description: "条件に合う要素だけを集めるメソッド。filterとも呼ばれる",
  },
  {
    term: "reject",
    reading: "りじぇくと",
    category: "ブロック・イテレータ",
    description: "条件に合わない要素だけを集めるメソッド",
  },
  {
    term: "reduce",
    reading: "りでゅーす",
    category: "ブロック・イテレータ",
    description: "要素を畳み込んで単一の値にするメソッド。injectとも呼ばれる",
  },
  {
    term: "flat_map",
    reading: "ふらっとまっぷ",
    category: "ブロック・イテレータ",
    description: "mapしてflattenする。ネストした配列を平坦化",
  },
  {
    term: "each_with_object",
    reading: "いーちうぃずおぶじぇくと",
    category: "ブロック・イテレータ",
    description: "オブジェクトを渡しながら走査するメソッド",
  },
  {
    term: "group_by",
    reading: "ぐるーぷばい",
    category: "ブロック・イテレータ",
    description: "ブロックの戻り値でグルーピングしてHashを返す",
  },
  {
    term: "sort_by",
    reading: "そーとばい",
    category: "ブロック・イテレータ",
    description: "ブロックの戻り値でソートするメソッド",
  },
  {
    term: "lazy",
    reading: "れいじー",
    category: "ブロック・イテレータ",
    description: "遅延評価のEnumeratorを返す。無限リストの処理に有用",
  },
  {
    term: "Enumerator",
    reading: "いにゅめれーたー",
    category: "ブロック・イテレータ",
    description: "外部イテレータ。eachの代わりに使える",
  },
  {
    term: "Enumerable",
    reading: "いにゅめらぶる",
    category: "ブロック・イテレータ",
    description: "each定義でmap・select等が使えるようになるモジュール",
  },
  {
    term: "times",
    reading: "たいむず",
    category: "ブロック・イテレータ",
    description: "指定回数ブロックを実行する。5.times { |i| ... }",
  },
  {
    term: "upto/downto",
    reading: "あっぷとぅ/だうんとぅ",
    category: "ブロック・イテレータ",
    description: "数値を増減させながらブロックを実行",
  },
  {
    term: "&:",
    reading: "あんぱーさんどころん",
    category: "ブロック・イテレータ",
    description: "Symbol#to_procの省略記法。.map(&:to_s)",
  },

  // モジュール・Gem
  {
    term: "module",
    reading: "もじゅーる",
    category: "モジュール・Gem",
    description: "モジュールを定義するキーワード。ミックスインと名前空間に使う",
  },
  {
    term: "include",
    reading: "いんくるーど",
    category: "モジュール・Gem",
    description: "モジュールのメソッドをインスタンスメソッドとして取り込む",
  },
  {
    term: "extend",
    reading: "えくすてんど",
    category: "モジュール・Gem",
    description: "モジュールのメソッドをクラスメソッドとして取り込む",
  },
  {
    term: "prepend",
    reading: "ぷりぺんど",
    category: "モジュール・Gem",
    description: "モジュールをメソッド探索順の先頭に挿入",
  },
  {
    term: "ミックスイン",
    reading: "みっくすいん",
    category: "モジュール・Gem",
    description: "include/prependでモジュールのメソッドをクラスに取り込む手法",
  },
  {
    term: "Comparable",
    reading: "こんぱらぶる",
    category: "モジュール・Gem",
    description: "<=>を定義すれば比較演算子が使えるモジュール",
  },
  {
    term: "gem",
    reading: "じぇむ",
    category: "モジュール・Gem",
    description: "Rubyのパッケージ。RubyGemsで管理",
  },
  {
    term: "Bundler",
    reading: "ばんどらー",
    category: "モジュール・Gem",
    description: "Gemの依存関係管理ツール",
  },
  {
    term: "Gemfile",
    reading: "じぇむふぁいる",
    category: "モジュール・Gem",
    description: "プロジェクトの依存Gemを記述するファイル",
  },
  {
    term: "Gemfile.lock",
    reading: "じぇむふぁいるろっく",
    category: "モジュール・Gem",
    description: "依存関係のバージョンを固定するファイル",
  },
  {
    term: "require",
    reading: "りくわいあ",
    category: "モジュール・Gem",
    description: "外部ファイル・Gemを読み込むメソッド",
  },
  {
    term: "require_relative",
    reading: "りくわいあれらてぃぶ",
    category: "モジュール・Gem",
    description: "相対パスでファイルを読み込むメソッド",
  },
  {
    term: "RubyGems",
    reading: "るびーじぇむず",
    category: "モジュール・Gem",
    description: "Rubyの標準パッケージマネージャ",
  },
  {
    term: "Rake",
    reading: "れいく",
    category: "モジュール・Gem",
    description: "Rubyのビルドツール。タスクランナーとして使われる",
  },
  {
    term: "Bundler.require",
    reading: "ばんどらーりくわいあ",
    category: "モジュール・Gem",
    description: "Gemfile内のすべてのGemを一括require",
  },

  // Web・API
  {
    term: "Rack",
    reading: "らっく",
    category: "Web・API",
    description: "RubyのWebサーバーとフレームワークの標準インターフェース",
  },
  {
    term: "Sinatra",
    reading: "しなとら",
    category: "Web・API",
    description: "軽量Webフレームワーク。簡単なAPIやプロトタイプに最適",
  },
  {
    term: "Rails",
    reading: "れいるず",
    category: "Web・API",
    description: "Ruby on Rails。フルスタックWebフレームワーク",
  },
  {
    term: "MVC",
    reading: "えむぶいしー",
    category: "Web・API",
    description: "Model-View-Controller。Railsの設計パターン",
  },
  {
    term: "Active Record",
    reading: "あくてぃぶれこーど",
    category: "Web・API",
    description: "RailsのORM。データベーステーブルをRubyオブジェクトにマッピング",
  },
  {
    term: "ERB",
    reading: "いーあーるびー",
    category: "Web・API",
    description: "Embedded Ruby。HTMLにRubyコードを埋め込むテンプレートエンジン",
  },
  {
    term: "マイグレーション",
    reading: "まいぐれーしょん",
    category: "Web・API",
    description: "データベーススキーマの変更をRubyコードで管理する仕組み",
  },
  {
    term: "ルーティング",
    reading: "るーてぃんぐ",
    category: "Web・API",
    description: "URLとコントローラのアクションを対応付ける設定",
  },
  {
    term: "RESTful",
    reading: "れすとふる",
    category: "Web・API",
    description: "リソース指向のAPI設計。CRUD操作をHTTPメソッドに対応",
  },
  {
    term: "JSON",
    reading: "じぇいそん",
    category: "Web・API",
    description: "データ交換フォーマット。require 'json'で標準利用可能",
  },
  {
    term: "API",
    reading: "えーぴーあい",
    category: "Web・API",
    description: "Application Programming Interface。外部サービスとの連携",
  },
  {
    term: "Puma",
    reading: "ぷーま",
    category: "Web・API",
    description: "高速・並行処理対応のRuby Webサーバー",
  },
  {
    term: "WEBrick",
    reading: "うぇぶりっく",
    category: "Web・API",
    description: "Ruby標準のWebサーバー。開発用途向け",
  },
  {
    term: "Net::HTTP",
    reading: "ねっとえいちてぃーてぃーぴー",
    category: "Web・API",
    description: "Ruby標準のHTTPクライアントライブラリ",
  },
  {
    term: "WebSocket",
    reading: "うぇぶそけっと",
    category: "Web・API",
    description: "双方向リアルタイム通信プロトコル",
  },

  // テスト
  {
    term: "Minitest",
    reading: "みにてすと",
    category: "テスト",
    description: "Ruby標準のテストフレームワーク",
  },
  {
    term: "RSpec",
    reading: "あーるすぺっく",
    category: "テスト",
    description: "BDDスタイルのテストフレームワーク。describe/it構文",
  },
  {
    term: "assert",
    reading: "あさーと",
    category: "テスト",
    description: "Minitestのアサーションメソッド。テスト条件を検証",
  },
  {
    term: "expect",
    reading: "えくすぺくと",
    category: "テスト",
    description: "RSpecのマッチャー。expect(x).to eq(y)",
  },
  {
    term: "describe",
    reading: "でぃすくらいぶ",
    category: "テスト",
    description: "RSpecでテスト対象を記述するメソッド",
  },
  {
    term: "it",
    reading: "いっと",
    category: "テスト",
    description: "RSpecでテストケースを記述するメソッド",
  },
  {
    term: "mock",
    reading: "もっく",
    category: "テスト",
    description: "テスト用の偽オブジェクト。外部依存を分離",
  },
  {
    term: "stub",
    reading: "すたぶ",
    category: "テスト",
    description: "メソッドの戻り値を固定するテスト手法",
  },
  {
    term: "TDD",
    reading: "てぃーでぃーでぃー",
    category: "テスト",
    description: "テスト駆動開発。テストを先に書いてから実装",
  },
  {
    term: "SimpleCov",
    reading: "しんぷるかぶ",
    category: "テスト",
    description: "テストカバレッジ計測ツール",
  },

  // ツール
  {
    term: "rbenv",
    reading: "あーるびーえんぶ",
    category: "ツール",
    description: "Rubyのバージョン管理ツール",
  },
  {
    term: "RVM",
    reading: "あーるぶいえむ",
    category: "ツール",
    description: "Ruby Version Manager。rbenvの代替",
  },
  {
    term: "RuboCop",
    reading: "るぼこっぷ",
    category: "ツール",
    description: "Rubyの静的解析・コードフォーマッター",
  },
  {
    term: "debug",
    reading: "でばっぐ",
    category: "ツール",
    description: "Ruby 3.1+標準のデバッガ",
  },
  {
    term: "Pry",
    reading: "ぷらい",
    category: "ツール",
    description: "高機能な対話型Ruby環境。irbの代替",
  },
  {
    term: "byebug",
    reading: "ばいばぐ",
    category: "ツール",
    description: "ステップ実行デバッガ",
  },
  {
    term: "YARD",
    reading: "やーど",
    category: "ツール",
    description: "Rubyのドキュメンテーションツール",
  },
  {
    term: "GitHub Actions",
    reading: "ぎっとはぶあくしょんず",
    category: "ツール",
    description: "CI/CDサービス。テスト自動化に使用",
  },
  {
    term: "Solargraph",
    reading: "そらーぐらふ",
    category: "ツール",
    description: "RubyのLanguage Server。エディタの補完・型チェック",
  },
  {
    term: "ruby-lsp",
    reading: "るびーえるえすぴー",
    category: "ツール",
    description: "Shopify製のRuby Language Server",
  },
];
