import { DartEditor } from "@/components/dart-editor";
import { LessonCompleteButton } from "@/components/lesson-complete-button";
import { LessonNav } from "@/components/lesson-nav";
import { getAllLessons } from "@/lib/lessons-data";

const lessons = getAllLessons("packages");

export default function PubspecYamlPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-10">
      <div className="mb-6">
        <span className="text-orange-400 text-sm font-semibold uppercase tracking-wide">パッケージ管理</span>
        <h1 className="text-3xl font-extrabold text-white mt-1 mb-3">pubspec.yaml</h1>
        <div className="bg-gray-900 rounded-lg p-4 text-gray-300 leading-relaxed">
          <p>
            <strong className="text-orange-300">pubspec.yaml</strong>はDartプロジェクトの設定ファイルです。
            プロジェクト名、バージョン、依存パッケージ、SDK制約などを定義します。
            このファイルはプロジェクトのルートに配置します。
          </p>
        </div>
      </div>

      <section className="mb-8">
        <h2 className="text-xl font-bold text-white mb-3">pubspec.yaml の構造</h2>
        <p className="text-gray-400 mb-4">
          pubspec.yamlの主要なフィールドを理解しましょう。
        </p>
        <DartEditor
          defaultCode={`// pubspec.yaml の詳細解説（Dartコードとして表示）

/*
name: my_dart_app              # パッケージ名（必須）
description: Dartアプリの説明  # 説明
version: 1.0.0                 # バージョン (major.minor.patch)
homepage: https://example.com  # ホームページURL

# Dart SDKの制約（必須）
environment:
  sdk: '>=3.0.0 <4.0.0'

# 本番依存パッケージ
dependencies:
  http: ^1.1.0
  path: ^1.8.3
  intl: ^0.18.0

# 開発時のみ使用するパッケージ
dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

# アセットファイル（Flutterのみ）
flutter:
  assets:
    - assets/images/
    - assets/data.json
*/

void explainVersioning() {
  final examples = {
    '1.0.0':        'メジャー.マイナー.パッチ',
    '1.0.0+1':      'バージョン+ビルド番号',
    '1.0.0-beta.1': 'プレリリース版',
  };
  examples.forEach((v, desc) => print('\$v: \$desc'));
}

void main() {
  print('=== pubspec.yaml バージョン表記 ===');
  explainVersioning();

  print('\\n=== バージョン制約 ===');
  final constraints = [
    '^2.0.0  →  >=2.0.0 <3.0.0（推奨）',
    'any     →  制約なし（非推奨）',
    '2.0.0   →  完全固定（非推奨）',
  ];
  constraints.forEach(print);
}`}
          expectedOutput={`=== pubspec.yaml バージョン表記 ===
1.0.0: メジャー.マイナー.パッチ
1.0.0+1: バージョン+ビルド番号
1.0.0-beta.1: プレリリース版

=== バージョン制約 ===
^2.0.0  →  >=2.0.0 <3.0.0（推奨）
any     →  制約なし（非推奨）
2.0.0   →  完全固定（非推奨）`}
        />
      </section>

      <section className="mb-8">
        <h2 className="text-xl font-bold text-white mb-3">pubspec.lock の役割</h2>
        <p className="text-gray-400 mb-4">
          <code className="text-orange-300">pubspec.lock</code>は実際にインストールされたバージョンを固定するファイルです。
        </p>
        <DartEditor
          defaultCode={`// pubspec.lock の役割について
/*
pubspec.lock は dart pub get 実行後に生成され、
実際のバージョンを固定します。

【重要なルール】
- アプリケーション: pubspec.lock を Git に含める
  → チームメンバーが同じバージョンを使用できる
- ライブラリ/パッケージ: pubspec.lock を Git に含めない
  → 利用者のプロジェクトでバージョン解決する

pubspec.lock の例:
# Generated by "dart pub get"
packages:
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dev"
    source: hosted
    version: "1.1.0"
  ...
*/

void main() {
  print('pubspec.yaml vs pubspec.lock:');
  print('');
  print('pubspec.yaml:');
  print('  - 手動で編集する設定ファイル');
  print('  - バージョン制約を指定');
  print('  - Gitに必ず含める');
  print('');
  print('pubspec.lock:');
  print('  - dart pub get が自動生成');
  print('  - 実際のバージョンを固定');
  print('  - アプリ: Gitに含める');
  print('  - ライブラリ: .gitignoreに追加');
}`}
          expectedOutput={`pubspec.yaml vs pubspec.lock:

pubspec.yaml:
  - 手動で編集する設定ファイル
  - バージョン制約を指定
  - Gitに必ず含める

pubspec.lock:
  - dart pub get が自動生成
  - 実際のバージョンを固定
  - アプリ: Gitに含める
  - ライブラリ: .gitignoreに追加`}
        />
      </section>

      <LessonCompleteButton lessonId="pubspec-yaml" categoryId="packages" />
      <LessonNav lessons={lessons} currentId="pubspec-yaml" basePath="/learn/packages" />
    </div>
  );
}
