export interface GlossaryTerm {
  term: string;
  reading?: string;
  description: string;
  category: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // ── 基礎 ────────────────────────────────────────────────────────────────────
  {
    term: "JVM",
    reading: "じぇいぶいえむ",
    description: "Java Virtual Machine。Javaバイトコードを実行する仮想マシン。プラットフォームに依存しない実行環境を提供し、「Write Once, Run Anywhere」を実現する。",
    category: "基礎",
  },
  {
    term: "JDK",
    reading: "じぇいでぃーけー",
    description: "Java Development Kit。Javaの開発に必要なツール一式。コンパイラ（javac）、JRE、デバッガ、各種ツールを含む。",
    category: "基礎",
  },
  {
    term: "JRE",
    reading: "じぇいあーるいー",
    description: "Java Runtime Environment。Javaプログラムを実行するための環境。JVMとクラスライブラリを含むが、開発ツールは含まない。",
    category: "基礎",
  },
  {
    term: "int",
    reading: "いんと",
    description: "32ビット符号付き整数のプリミティブ型。-2,147,483,648 から 2,147,483,647 までの値を格納できる。ラッパークラスは Integer。",
    category: "基礎",
  },
  {
    term: "String",
    reading: "すとりんぐ",
    description: "文字列を表すイミュータブル（不変）なクラス。ダブルクォートで囲んで生成する。一度作成すると内容を変更できない。",
    category: "基礎",
  },
  {
    term: "boolean",
    reading: "ぶーりあん",
    description: "true または false の2値を持つプリミティブ型。条件分岐や論理演算で使用する。ラッパークラスは Boolean。",
    category: "基礎",
  },
  {
    term: "double",
    reading: "だぶる",
    description: "64ビット浮動小数点数のプリミティブ型。小数を扱う際のデフォルトの型。精度が必要な場合は BigDecimal を使う。",
    category: "基礎",
  },
  {
    term: "float",
    reading: "ふろーと",
    description: "32ビット浮動小数点数のプリミティブ型。リテラルには末尾にfを付ける（例: 3.14f）。通常は精度の高い double が推奨される。",
    category: "基礎",
  },
  {
    term: "long",
    reading: "ろんぐ",
    description: "64ビット符号付き整数のプリミティブ型。int では足りない大きな整数値に使用する。リテラルには末尾にLを付ける。",
    category: "基礎",
  },
  {
    term: "void",
    reading: "ぼいど",
    description: "メソッドが値を返さないことを示すキーワード。戻り値のないメソッドの宣言に使用する。変数の型としては使えない。",
    category: "基礎",
  },
  {
    term: "null",
    reading: "なる",
    description: "参照型変数がどのオブジェクトも指していないことを表すリテラル。nullに対してメソッドを呼ぶと NullPointerException が発生する。",
    category: "基礎",
  },
  {
    term: "static",
    reading: "すたてぃっく",
    description: "クラスに属するメンバ（フィールドやメソッド）を宣言するキーワード。インスタンスを作成せずにアクセスできる。mainメソッドには必ず付ける。",
    category: "基礎",
  },
  {
    term: "final",
    reading: "ふぁいなる",
    description: "再代入不可の変数、オーバーライド不可のメソッド、継承不可のクラスを宣言するキーワード。定数の定義に使われる。",
    category: "基礎",
  },
  {
    term: "new",
    reading: "にゅー",
    description: "オブジェクトのインスタンスを生成するキーワード。コンストラクタを呼び出し、ヒープ領域にメモリを確保する。",
    category: "基礎",
  },
  {
    term: "this",
    reading: "じす",
    description: "現在のインスタンスへの参照。フィールドとローカル変数の名前が衝突する場合の区別や、コンストラクタの委譲に使う。",
    category: "基礎",
  },
  {
    term: "super",
    reading: "すーぱー",
    description: "親クラスへの参照。親クラスのコンストラクタやメソッドを呼び出す際に使う。super()はコンストラクタの先頭で呼ぶ必要がある。",
    category: "基礎",
  },
  {
    term: "package",
    reading: "ぱっけーじ",
    description: "クラスを論理的にグループ化する仕組み。ディレクトリ構造と対応し、名前空間の衝突を防ぐ。慣例的に逆ドメイン名を使う。",
    category: "基礎",
  },
  {
    term: "import",
    reading: "いんぽーと",
    description: "他のパッケージのクラスを使用可能にするキーワード。java.util.* で一括インポートも可能。java.lang パッケージは自動インポートされる。",
    category: "基礎",
  },
  {
    term: "Enum",
    reading: "いなむ",
    description: "定数の集合を定義する特殊なクラス。enum キーワードで宣言し、型安全な定数として使う。メソッドやフィールドも持てる。",
    category: "基礎",
  },
  {
    term: "Annotation",
    reading: "あのてーしょん",
    description: "コードにメタデータを付加する仕組み。@Override、@Deprecated、@SuppressWarnings などが標準で提供される。フレームワークでも広く活用される。",
    category: "基礎",
  },
  // ── OOP ──────────────────────────────────────────────────────────────────
  {
    term: "class",
    reading: "くらす",
    description: "オブジェクトの設計図となる型定義。フィールド（データ）とメソッド（処理）をまとめ、カプセル化・継承・ポリモーフィズムを実現する。",
    category: "OOP",
  },
  {
    term: "object",
    reading: "おぶじぇくと",
    description: "クラスから生成されたインスタンス。new キーワードで作成し、フィールドの値とメソッドの振る舞いを持つ実体。",
    category: "OOP",
  },
  {
    term: "interface",
    reading: "いんたーふぇーす",
    description: "メソッドのシグネチャを定義する契約。implements で実装する。Java 8以降はデフォルトメソッドと static メソッドも定義可能。",
    category: "OOP",
  },
  {
    term: "abstract",
    reading: "あぶすとらくと",
    description: "抽象クラスまたは抽象メソッドを宣言するキーワード。抽象クラスはインスタンス化できず、サブクラスに実装を強制する。",
    category: "OOP",
  },
  {
    term: "extends",
    reading: "えくすてんず",
    description: "クラスの継承を宣言するキーワード。Javaは単一継承のみサポートし、1つのクラスしか extends できない。",
    category: "OOP",
  },
  {
    term: "implements",
    reading: "いんぷれめんつ",
    description: "インターフェースの実装を宣言するキーワード。1つのクラスで複数のインターフェースを実装できる。",
    category: "OOP",
  },
  {
    term: "@Override",
    reading: "おーばーらいど",
    description: "親クラスのメソッドをオーバーライドしていることを示すアノテーション。コンパイル時に正しくオーバーライドされているか検証される。",
    category: "OOP",
  },
  {
    term: "overload",
    reading: "おーばーろーど",
    description: "同じ名前で引数の型や数が異なるメソッドを複数定義すること。コンパイル時に適切なメソッドが選択される（静的多態性）。",
    category: "OOP",
  },
  {
    term: "カプセル化",
    reading: "かぷせるか",
    description: "フィールドを private にし、getter/setter メソッドを通じてアクセスする原則。内部実装を隠蔽し、不正な操作を防ぐ。",
    category: "OOP",
  },
  {
    term: "ポリモーフィズム",
    reading: "ぽりもーふぃずむ",
    description: "親クラスやインターフェースの型で子クラスのオブジェクトを扱い、実行時に適切なメソッドが呼ばれる仕組み。コードの柔軟性を高める。",
    category: "OOP",
  },
  {
    term: "Serializable",
    reading: "しりあらいざぶる",
    description: "オブジェクトをバイトストリームに変換（シリアライズ）可能であることを示すマーカーインターフェース。ネットワーク通信やファイル保存に使う。",
    category: "OOP",
  },
  // ── コレクション ──────────────────────────────────────────────────────────
  {
    term: "ArrayList",
    reading: "あれいりすと",
    description: "可変長配列の実装クラス。内部的に配列を使用し、ランダムアクセスがO(1)。末尾への追加は償却O(1)だが、途中への挿入はO(n)。",
    category: "コレクション",
  },
  {
    term: "HashMap",
    reading: "はっしゅまっぷ",
    description: "キーと値のペアを格納するハッシュテーブル実装。put/get/containsKey が平均O(1)。キーの順序は保証されない。",
    category: "コレクション",
  },
  {
    term: "HashSet",
    reading: "はっしゅせっと",
    description: "重複なしの要素を格納するコレクション。内部的にHashMapを使用し、add/contains/remove が平均O(1)。順序は保証されない。",
    category: "コレクション",
  },
  {
    term: "Iterator",
    reading: "いてれーた",
    description: "コレクションの要素を順次アクセスするためのインターフェース。hasNext() と next() で要素を走査し、remove() で安全に削除できる。",
    category: "コレクション",
  },
  {
    term: "Generics",
    reading: "じぇねりくす",
    description: "型パラメータを使って汎用的なクラスやメソッドを定義する仕組み。List<String> のように型安全なコレクションを実現する。型消去により実行時には型情報が消える。",
    category: "コレクション",
  },
  {
    term: "Comparable",
    reading: "こんぱらぶる",
    description: "自然順序による比較を定義するインターフェース。compareTo() メソッドを実装し、Collections.sort() などで使われる。",
    category: "コレクション",
  },
  {
    term: "Comparator",
    reading: "こんぱれーた",
    description: "カスタムの比較ロジックを定義するインターフェース。compare() メソッドを実装し、ソートの順序を柔軟に指定できる。ラムダ式で簡潔に記述可能。",
    category: "コレクション",
  },
  {
    term: "Iterable",
    reading: "いてらぶる",
    description: "拡張forループ（for-each）で走査可能なことを示すインターフェース。iterator() メソッドを提供する。すべてのCollectionが実装している。",
    category: "コレクション",
  },
  {
    term: "LinkedList",
    reading: "りんくどりすと",
    description: "双方向連結リストの実装クラス。先頭・末尾への挿入がO(1)だが、ランダムアクセスはO(n)。Deque としても使える。",
    category: "コレクション",
  },
  {
    term: "TreeMap",
    reading: "つりーまっぷ",
    description: "赤黒木で実装されたソート済みマップ。キーの自然順序または Comparator で自動ソートされる。検索・挿入・削除はO(log n)。",
    category: "コレクション",
  },
  // ── ラムダ・Stream ──────────────────────────────────────────────────────────
  {
    term: "Lambda",
    reading: "らむだ",
    description: "匿名関数を簡潔に記述する構文（Java 8以降）。(引数) -> 式 の形式で、関数型インターフェースの実装として使用する。",
    category: "ラムダ・Stream",
  },
  {
    term: "Stream",
    reading: "すとりーむ",
    description: "コレクションの要素を関数型スタイルで処理するAPI（Java 8以降）。filter, map, reduce, collect などの操作をパイプラインで連鎖する。",
    category: "ラムダ・Stream",
  },
  {
    term: "Optional",
    reading: "おぷしょなる",
    description: "値が存在するかもしれないことを明示する型（Java 8以降）。nullの代わりに使い、orElse, ifPresent, map などで安全に値を扱う。",
    category: "ラムダ・Stream",
  },
  {
    term: "メソッド参照",
    reading: "めそっどさんしょう",
    description: "既存のメソッドをラムダ式の代わりに参照する記法。System.out::println, String::length のように :: 演算子で記述する。",
    category: "ラムダ・Stream",
  },
  {
    term: "関数型インターフェース",
    reading: "かんすうがたいんたーふぇーす",
    description: "抽象メソッドを1つだけ持つインターフェース。@FunctionalInterface で宣言し、ラムダ式のターゲット型として使う。Predicate, Function, Consumer 等がある。",
    category: "ラムダ・Stream",
  },
  {
    term: "Predicate",
    reading: "ぷれでぃけーと",
    description: "引数を1つ取り boolean を返す関数型インターフェース。Stream の filter() やコレクションの removeIf() で条件判定に使われる。",
    category: "ラムダ・Stream",
  },
  {
    term: "Collectors",
    reading: "これくたーず",
    description: "Stream の終端操作 collect() に渡すコレクタのユーティリティクラス。toList(), toMap(), groupingBy(), joining() などを提供する。",
    category: "ラムダ・Stream",
  },
  {
    term: "map / flatMap",
    reading: "まっぷ / ふらっとまっぷ",
    description: "Stream やOptional の中間操作。map は要素を変換し、flatMap はネストされたストリームを平坦化しながら変換する。",
    category: "ラムダ・Stream",
  },
  // ── Web開発 ──────────────────────────────────────────────────────────────────
  {
    term: "Spring",
    reading: "すぷりんぐ",
    description: "Javaの代表的なアプリケーションフレームワーク。DI（依存性注入）とAOP（アスペクト指向）を核とし、企業向けアプリケーション開発を支援する。",
    category: "Web開発",
  },
  {
    term: "Spring Boot",
    reading: "すぷりんぐぶーと",
    description: "Spring をベースにした高速開発フレームワーク。自動設定、組み込みサーバー、スターターにより最小限の設定でアプリケーションを構築できる。",
    category: "Web開発",
  },
  {
    term: "Bean",
    reading: "びーん",
    description: "Spring コンテナが管理するオブジェクト。@Component, @Service, @Repository などのアノテーションで登録し、DIコンテナからインジェクションされる。",
    category: "Web開発",
  },
  {
    term: "DI",
    reading: "でぃーあい",
    description: "Dependency Injection（依存性注入）。オブジェクトの依存関係を外部から注入する設計パターン。@Autowired でコンストラクタ・フィールド注入を行う。",
    category: "Web開発",
  },
  {
    term: "AOP",
    reading: "えーおーぴー",
    description: "Aspect-Oriented Programming（アスペクト指向プログラミング）。ロギングやトランザクション管理などの横断的関心事をコードから分離する手法。",
    category: "Web開発",
  },
  {
    term: "REST",
    reading: "れすと",
    description: "Representational State Transfer。HTTPメソッド（GET, POST, PUT, DELETE）でリソースを操作するアーキテクチャスタイル。Web APIの標準的な設計手法。",
    category: "Web開発",
  },
  {
    term: "JPA",
    reading: "じぇいぴーえー",
    description: "Java Persistence API。Javaオブジェクトとリレーショナルデータベースをマッピングする標準仕様。Hibernateが代表的な実装。",
    category: "Web開発",
  },
  {
    term: "Entity",
    reading: "えんてぃてぃ",
    description: "JPAでデータベーステーブルにマッピングされるクラス。@Entity アノテーションで宣言し、@Id で主キーを指定する。",
    category: "Web開発",
  },
  {
    term: "Repository",
    reading: "りぽじとり",
    description: "データアクセス層を抽象化するインターフェース。Spring Data JPA では JpaRepository を継承するだけで基本的なCRUD操作が自動実装される。",
    category: "Web開発",
  },
  // ── 並行処理 ──────────────────────────────────────────────────────────────────
  {
    term: "Thread",
    reading: "すれっど",
    description: "並行処理の実行単位。Thread クラスを継承するか Runnable を実装して作成し、start() で実行を開始する。",
    category: "並行処理",
  },
  {
    term: "synchronized",
    reading: "しんくろないずど",
    description: "排他制御を行うキーワード。メソッドまたはブロックに付けて、同時に1つのスレッドだけがアクセスできるようにする。",
    category: "並行処理",
  },
  {
    term: "volatile",
    reading: "ぼらたいる",
    description: "変数の値がメインメモリから直接読み書きされることを保証するキーワード。スレッド間の可視性問題を解決するが、原子性は保証しない。",
    category: "並行処理",
  },
  {
    term: "Runnable",
    reading: "らなぶる",
    description: "スレッドで実行する処理を定義する関数型インターフェース。run() メソッドを実装し、Thread のコンストラクタに渡す。ラムダ式で記述可能。",
    category: "並行処理",
  },
  {
    term: "Callable",
    reading: "こーらぶる",
    description: "値を返し例外をスローできるタスクを定義するインターフェース。Runnable と異なり、call() メソッドが戻り値を持つ。ExecutorServiceで使用する。",
    category: "並行処理",
  },
  {
    term: "Future",
    reading: "ふゅーちゃー",
    description: "非同期処理の結果を表すインターフェース。get() で結果を取得（ブロッキング）し、isDone() で完了チェック、cancel() でキャンセルできる。",
    category: "並行処理",
  },
  {
    term: "ExecutorService",
    reading: "えくぜきゅーたーさーびす",
    description: "スレッドプールを管理するインターフェース。Executors.newFixedThreadPool() 等で生成し、submit() でタスクを投入する。直接Threadを使うより推奨される。",
    category: "並行処理",
  },
  {
    term: "CompletableFuture",
    reading: "こんぷりーたぶるふゅーちゃー",
    description: "非同期処理の合成が可能な Future 拡張（Java 8以降）。thenApply, thenCompose, thenCombine 等で非同期パイプラインを構築できる。",
    category: "並行処理",
  },
  // ── ビルド ──────────────────────────────────────────────────────────────────
  {
    term: "Maven",
    reading: "めいぶん",
    description: "XMLベースのビルド・依存関係管理ツール。pom.xml にプロジェクト設定と依存ライブラリを記述する。Javaのデファクトスタンダード。",
    category: "ビルド",
  },
  {
    term: "Gradle",
    reading: "ぐれいどる",
    description: "GroovyまたはKotlinベースのビルドツール。build.gradle(.kts) で設定を記述し、Mavenより柔軟で高速。Android開発の標準ビルドツール。",
    category: "ビルド",
  },
  {
    term: "JUnit",
    reading: "じぇいゆにっと",
    description: "Javaの標準的なユニットテストフレームワーク。@Test でテストメソッドを定義し、assertEquals 等のアサーションで検証する。現在の最新はJUnit 5。",
    category: "ビルド",
  },
  {
    term: "Mockito",
    reading: "もきーと",
    description: "Javaのモッキングフレームワーク。テスト対象の依存オブジェクトをモック化し、振る舞いを定義してユニットテストを独立させる。",
    category: "ビルド",
  },
  {
    term: "JAR",
    reading: "じゃー",
    description: "Java ARchive。コンパイル済みクラスファイルやリソースをZIP形式でまとめたファイル。ライブラリの配布や実行可能ファイルとして使われる。",
    category: "ビルド",
  },
  {
    term: "WAR",
    reading: "うぉー",
    description: "Web Application Archive。Webアプリケーションのデプロイに使われるアーカイブファイル。Servletコンテナ（Tomcat等）にデプロイして実行する。",
    category: "ビルド",
  },
  {
    term: "Exception",
    reading: "えくせぷしょん",
    description: "実行時に発生するエラーを表すクラス。try-catch で捕捉し、throws で伝播させる。checked と unchecked（RuntimeException）の2種類がある。",
    category: "基礎",
  },
  {
    term: "try-catch",
    reading: "とらいきゃっち",
    description: "例外処理の構文。try ブロックで例外が発生する可能性のあるコードを囲み、catch で例外を捕捉する。finally で後処理、try-with-resources でリソースを自動解放する。",
    category: "基礎",
  },
  {
    term: "throws",
    reading: "すろーず",
    description: "メソッドが例外をスローする可能性があることを宣言するキーワード。checked例外はメソッド宣言に throws を付けるか、try-catch で処理する必要がある。",
    category: "基礎",
  },
];
