export type GlossaryCategory = "html" | "css" | "javascript" | "symbol" | "general";

export interface GlossaryEntry {
  id: string;
  term: string;
  reading?: string;
  category: GlossaryCategory;
  shortDesc: string;
  detail: string;
  example?: string;
  related?: string[];
}

export const CATEGORY_LABELS: Record<GlossaryCategory, { label: string; color: string }> = {
  html: { label: "HTML", color: "orange" },
  css: { label: "CSS", color: "blue" },
  javascript: { label: "JavaScript", color: "yellow" },
  symbol: { label: "記号", color: "purple" },
  general: { label: "一般", color: "gray" },
};

export const GLOSSARY: GlossaryEntry[] = [
  // ---- HTML ----
  {
    id: "html-tag",
    term: "<tag>",
    category: "html",
    shortDesc: "HTML要素を囲む記号",
    detail: "HTMLでは < と > で囲んだものを「タグ」と呼びます。開始タグ <tag> と終了タグ </tag> でコンテンツを挟んで要素を作ります。タグ名はブラウザに「この部分は何か」を伝える役割があります。",
    example: "<h1>見出し</h1>\n<p>段落</p>",
    related: ["html-element", "html-attribute"],
  },
  {
    id: "html-element",
    term: "要素（Element）",
    reading: "ようそ",
    category: "html",
    shortDesc: "開始タグ＋内容＋終了タグのセット",
    detail: "HTML要素は開始タグ、内容（コンテンツ）、終了タグで構成されます。例えば <p>こんにちは</p> 全体が1つのp要素です。要素はネスト（入れ子）にすることもできます。",
    example: "<div>\n  <p>これが要素です</p>\n</div>",
  },
  {
    id: "html-attribute",
    term: "属性（Attribute）",
    reading: "ぞくせい",
    category: "html",
    shortDesc: "タグに追加情報を与えるもの",
    detail: "属性は開始タグの中に書き、要素に追加の情報を与えます。属性名=\"値\" の形式で記述します。href、src、class、id などが代表的な属性です。",
    example: '<a href="https://example.com" target="_blank">リンク</a>\n<img src="photo.jpg" alt="写真">',
  },
  {
    id: "html-doctype",
    term: "<!DOCTYPE html>",
    category: "html",
    shortDesc: "HTMLのバージョン宣言",
    detail: "HTMLファイルの最初に書く宣言で、ブラウザにこのファイルがHTML5であることを伝えます。これがないとブラウザが古い互換モードで表示してしまうことがあります。",
    example: "<!DOCTYPE html>\n<html>\n  ...\n</html>",
  },
  {
    id: "html-div",
    term: "<div>",
    category: "html",
    shortDesc: "汎用のブロックコンテナ",
    detail: "div要素はそれ自体には意味を持たない汎用的な「箱」です。CSSでスタイルを当てたり、JavaScriptで操作するためのグループ化に使います。ブロック要素なので前後に改行が入ります。",
    example: '<div class="card">\n  <h2>タイトル</h2>\n  <p>内容</p>\n</div>',
  },
  {
    id: "html-span",
    term: "<span>",
    category: "html",
    shortDesc: "汎用のインラインコンテナ",
    detail: "span要素はdivのインライン版です。テキストの一部だけにスタイルを当てたい時に使います。前後に改行は入らず、テキストの中に置けます。",
    example: '<p>ここは<span style="color:red">赤い文字</span>です</p>',
  },
  {
    id: "html-a",
    term: "<a>",
    reading: "アンカー",
    category: "html",
    shortDesc: "ハイパーリンクを作るタグ",
    detail: "a（anchor）タグは他のページやURLへのリンクを作ります。href属性でリンク先を指定します。target=\"_blank\" で新しいタブで開くようにできます。",
    example: '<a href="https://google.com">Googleへ</a>',
  },
  {
    id: "html-img",
    term: "<img>",
    category: "html",
    shortDesc: "画像を表示するタグ",
    detail: "img要素は画像を埋め込みます。src属性で画像のURL、alt属性で代替テキストを指定します。閉じタグは不要な「空要素」です。",
    example: '<img src="photo.jpg" alt="風景写真" width="300">',
  },
  {
    id: "html-ul-ol",
    term: "<ul> / <ol>",
    category: "html",
    shortDesc: "リストを作るタグ",
    detail: "ul（unordered list）は順序なしリスト（・で表示）、ol（ordered list）は順序ありリスト（1,2,3...で表示）を作ります。中に<li>要素を並べます。",
    example: "<ul>\n  <li>りんご</li>\n  <li>バナナ</li>\n</ul>",
  },
  {
    id: "html-form",
    term: "<form>",
    category: "html",
    shortDesc: "ユーザー入力を収集するフォーム",
    detail: "form要素はユーザーからのデータ入力を受け付ける領域を作ります。中にinput、textarea、button、selectなどの入力要素を配置します。action属性で送信先を指定できます。",
    example: '<form>\n  <input type="text" placeholder="名前">\n  <button type="submit">送信</button>\n</form>',
  },

  // ---- CSS ----
  {
    id: "css-selector",
    term: "セレクタ（Selector）",
    category: "css",
    shortDesc: "スタイルを適用する対象を指定",
    detail: "セレクタはCSSルールの最初に書き、どのHTML要素にスタイルを適用するかを指定します。タグ名（h1）、クラス（.card）、ID（#main）などの種類があります。",
    example: "h1 { color: blue; }      /* タグ名 */\n.card { padding: 20px; }  /* クラス */\n#main { width: 100%; }   /* ID */",
  },
  {
    id: "css-property",
    term: "プロパティ（Property）",
    category: "css",
    shortDesc: "何を変えるかを指定",
    detail: "プロパティはセレクタの中で「何を」変えるかを指定します。color（文字色）、font-size（文字サイズ）、background（背景）、margin（余白）などがあります。",
    example: "p {\n  color: #333;        /* 文字色 */\n  font-size: 16px;    /* 文字サイズ */\n  margin-bottom: 12px; /* 下の余白 */\n}",
  },
  {
    id: "css-class",
    term: ".class",
    category: "css",
    shortDesc: "クラスセレクタ（ドットで始まる）",
    detail: "ピリオド(.)で始まるセレクタはクラスセレクタです。HTMLのclass属性と対応し、同じクラス名を持つすべての要素にスタイルが適用されます。複数の要素に同じスタイルを当てたい時に使います。",
    example: "/* CSS */\n.highlight { background: yellow; }\n\n<!-- HTML -->\n<p class=\"highlight\">黄色い背景</p>",
  },
  {
    id: "css-id",
    term: "#id",
    category: "css",
    shortDesc: "IDセレクタ（シャープで始まる）",
    detail: "シャープ(#)で始まるセレクタはIDセレクタです。ページ内で一意（ユニーク）な要素に使います。同じIDは1ページに1つだけが原則です。クラスより優先度が高いです。",
    example: "/* CSS */\n#header { background: navy; }\n\n<!-- HTML -->\n<div id=\"header\">ヘッダー</div>",
  },
  {
    id: "css-boxmodel",
    term: "ボックスモデル",
    category: "css",
    shortDesc: "すべての要素を囲む4層構造",
    detail: "すべてのHTML要素は「content（内容）→ padding（内側余白）→ border（枠線）→ margin（外側余白）」の4層のボックスとして扱われます。この概念を理解することがCSSレイアウトの基本です。",
    example: ".box {\n  margin: 20px;     /* 外側 */\n  border: 2px solid; /* 枠線 */\n  padding: 16px;    /* 内側 */\n  /* content はここ */\n}",
  },
  {
    id: "css-flexbox",
    term: "Flexbox",
    reading: "フレックスボックス",
    category: "css",
    shortDesc: "要素を柔軟に配置するレイアウト",
    detail: "display: flex を親要素に指定すると、子要素を横並び・縦並び・均等配置など柔軟にレイアウトできます。justify-content（主軸方向の配置）とalign-items（交差軸方向の配置）が基本です。",
    example: ".container {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  gap: 12px;\n}",
  },
  {
    id: "css-grid",
    term: "Grid",
    reading: "グリッド",
    category: "css",
    shortDesc: "2次元のグリッドレイアウト",
    detail: "CSS Gridは行と列の2次元グリッドでレイアウトを組むシステムです。grid-template-columnsとgrid-template-rowsでグリッドの構造を定義します。複雑なレイアウトに最適です。",
    example: ".grid {\n  display: grid;\n  grid-template-columns: 1fr 1fr 1fr;\n  gap: 16px;\n}",
  },
  {
    id: "css-responsive",
    term: "メディアクエリ",
    category: "css",
    shortDesc: "画面サイズに応じてスタイルを変更",
    detail: "@media ルールを使うと、画面幅などの条件に応じて異なるスタイルを適用できます。これにより1つのCSSでPC・タブレット・スマホすべてに対応するレスポンシブデザインが実現できます。",
    example: "@media (max-width: 768px) {\n  .container {\n    flex-direction: column;\n  }\n}",
  },

  // ---- JavaScript ----
  {
    id: "js-variable",
    term: "変数（Variable）",
    reading: "へんすう",
    category: "javascript",
    shortDesc: "データを入れる名前付きの箱",
    detail: "変数はデータを保存する「名前付きの箱」です。letは後から値を変更できる変数、constは変更できない定数を宣言します。varは古い書き方で、現在はletとconstが推奨されます。",
    example: 'let count = 0;        // 変更可能\nconst name = "太郎";   // 変更不可\ncount = 10;            // OK\n// name = "花子";      // エラー！',
  },
  {
    id: "js-function",
    term: "関数（Function）",
    reading: "かんすう",
    category: "javascript",
    shortDesc: "処理をまとめて名前をつけたもの",
    detail: "関数は一連の処理をまとめて再利用可能にしたものです。function宣言またはアロー関数(=>)で定義し、引数でデータを受け取り、returnで結果を返せます。",
    example: "// 通常の関数\nfunction greet(name) {\n  return `こんにちは、${name}！`;\n}\n\n// アロー関数\nconst add = (a, b) => a + b;",
  },
  {
    id: "js-array",
    term: "配列（Array）",
    reading: "はいれつ",
    category: "javascript",
    shortDesc: "複数のデータを順番に格納するリスト",
    detail: "配列は複数の値を順番に格納するデータ構造です。[  ]で作り、インデックス（0から始まる番号）でアクセスします。push、map、filterなど多くのメソッドがあります。",
    example: 'const fruits = ["りんご", "バナナ", "みかん"];\nconsole.log(fruits[0]);  // "りんご"\nfruits.push("ぶどう");   // 末尾に追加\nconsole.log(fruits.length); // 4',
  },
  {
    id: "js-object",
    term: "オブジェクト（Object）",
    category: "javascript",
    shortDesc: "キーと値のペアでデータを管理",
    detail: "オブジェクトは「キー: 値」のペアでデータを管理する構造です。{ } で作り、ドット記法（obj.key）やブラケット記法（obj[\"key\"]）でアクセスします。",
    example: 'const user = {\n  name: "太郎",\n  age: 25,\n  isStudent: true,\n};\nconsole.log(user.name); // "太郎"',
  },
  {
    id: "js-dom",
    term: "DOM",
    reading: "ドム",
    category: "javascript",
    shortDesc: "HTMLをJavaScriptから操作するための仕組み",
    detail: "DOM（Document Object Model）はHTMLをツリー構造のオブジェクトとして表現したものです。document.querySelector()やelement.textContentなどを使い、JavaScriptからHTML要素を取得・変更・追加・削除できます。",
    example: 'const el = document.querySelector("#title");\nel.textContent = "新しいタイトル";\nel.style.color = "red";',
  },
  {
    id: "js-event",
    term: "イベント（Event）",
    category: "javascript",
    shortDesc: "ユーザー操作や出来事の通知",
    detail: "イベントはクリック、キー入力、スクロールなどのユーザー操作やブラウザの出来事です。addEventListener()でイベントを検知し、コールバック関数で処理を実行します。",
    example: 'button.addEventListener("click", () => {\n  alert("クリックされました！");\n});\n\ninput.addEventListener("input", (e) => {\n  console.log(e.target.value);\n});',
  },
  {
    id: "js-if",
    term: "if / else",
    category: "javascript",
    shortDesc: "条件によって処理を分岐",
    detail: "if文は条件式がtrueの時だけブロック内の処理を実行します。elseで「それ以外」、else ifで追加の条件を指定できます。条件式には比較演算子（===、<、>など）を使います。",
    example: 'if (age >= 20) {\n  console.log("成人です");\n} else if (age >= 13) {\n  console.log("ティーンです");\n} else {\n  console.log("こどもです");\n}',
  },
  {
    id: "js-loop",
    term: "ループ（for / while）",
    category: "javascript",
    shortDesc: "同じ処理を繰り返し実行",
    detail: "forループは指定回数だけ処理を繰り返します。whileループは条件がtrueの間ずっと繰り返します。配列を扱う場合はfor...ofやforEach()も便利です。",
    example: "for (let i = 0; i < 5; i++) {\n  console.log(i); // 0,1,2,3,4\n}\n\nconst arr = [1,2,3];\narr.forEach(n => console.log(n));",
  },
  {
    id: "js-async",
    term: "async / await",
    reading: "エイシンク / アウェイト",
    category: "javascript",
    shortDesc: "非同期処理を同期的に書ける構文",
    detail: "async関数の中でawaitを使うと、Promiseの完了を待ってから次の行に進めます。API通信やファイル読み込みなど、時間のかかる処理を直感的に書けます。",
    example: 'async function fetchData() {\n  const res = await fetch("/api/data");\n  const data = await res.json();\n  console.log(data);\n}',
  },

  // ---- 記号 ----
  {
    id: "sym-angle-brackets",
    term: "< >",
    reading: "山括弧 / アングルブラケット",
    category: "symbol",
    shortDesc: "HTMLタグを囲む記号",
    detail: "< と > はHTMLでタグを表すために使われます。<tag> が開始タグ、</tag> が終了タグです。JavaScriptでは比較演算子（より小さい/より大きい）としても使います。",
    example: "<p>HTMLのタグ</p>\n\n// JSでは比較\nif (a < b) { ... }",
  },
  {
    id: "sym-curly-braces",
    term: "{ }",
    reading: "波括弧 / カーリーブレース",
    category: "symbol",
    shortDesc: "ブロックやオブジェクトを囲む",
    detail: "CSSではプロパティのブロックを囲みます。JavaScriptではif文やfor文のブロック、オブジェクトリテラル、関数の本体を囲みます。プログラミングで最も頻繁に使う記号の一つです。",
    example: "/* CSS */\nh1 { color: red; }\n\n// JS - ブロック\nif (x) { ... }\n\n// JS - オブジェクト\nconst obj = { key: \"value\" };",
  },
  {
    id: "sym-parentheses",
    term: "( )",
    reading: "丸括弧 / パーレン",
    category: "symbol",
    shortDesc: "関数呼び出しや条件式で使用",
    detail: "JavaScriptでは関数の呼び出し func()、引数の指定 func(arg)、条件式の囲み if (条件) に使います。CSSではrgb()やcalc()など関数表記にも使われます。",
    example: "console.log(\"hello\");  // 関数呼び出し\nif (age > 20) { ... }  // 条件式\ncalc(100% - 20px)      // CSS関数",
  },
  {
    id: "sym-square-brackets",
    term: "[ ]",
    reading: "角括弧 / ブラケット",
    category: "symbol",
    shortDesc: "配列やプロパティアクセスで使用",
    detail: "JavaScriptでは配列リテラル [1, 2, 3] の作成と、配列やオブジェクトのプロパティアクセス arr[0]、obj[\"key\"] に使います。CSSでは属性セレクタ [type=\"text\"] に使います。",
    example: 'const arr = [1, 2, 3];\narr[0];  // 1\n\nobj["name"];  // プロパティアクセス\n\n/* CSS属性セレクタ */\ninput[type="text"] { ... }',
  },
  {
    id: "sym-semicolon",
    term: ";",
    reading: "セミコロン",
    category: "symbol",
    shortDesc: "文の終わりを示す",
    detail: "CSSでは各プロパティの区切りに必須です。JavaScriptでは文の終わりに付けます（自動挿入されるため省略可能な場合もありますが、付けるのが安全です）。",
    example: "/* CSS - 必須 */\ncolor: red;\nfont-size: 16px;\n\n// JS - 推奨\nlet x = 10;\nconsole.log(x);",
  },
  {
    id: "sym-colon",
    term: ":",
    reading: "コロン",
    category: "symbol",
    shortDesc: "プロパティと値の区切り",
    detail: "CSSではプロパティ名と値の間に使います（color: red）。JavaScriptではオブジェクトのキーと値の間に使います（{ name: \"太郎\" }）。三項演算子の一部としても使います。",
    example: "/* CSS */\ncolor: blue;\n\n// JSオブジェクト\n{ key: \"value\" }\n\n// 三項演算子\nx > 0 ? \"正\" : \"負\"",
  },
  {
    id: "sym-dot",
    term: ".",
    reading: "ドット / ピリオド",
    category: "symbol",
    shortDesc: "プロパティアクセスやクラス指定",
    detail: "CSSではクラスセレクタの前に付けます（.card）。JavaScriptではオブジェクトのプロパティアクセスに使います（obj.name）。メソッドチェーンにも使います。",
    example: "/* CSS */\n.card { ... }\n\n// JS\nconsole.log(\"hello\");\narray.map(x => x * 2);",
  },
  {
    id: "sym-hash",
    term: "#",
    reading: "シャープ / ハッシュ",
    category: "symbol",
    shortDesc: "IDセレクタやカラーコード",
    detail: "CSSではIDセレクタの前に付けます（#header）。カラーコードの前にも使います（#FF0000 = 赤）。HTMLではページ内リンクのアンカーにも使います。",
    example: "/* CSS */\n#header { ... }\ncolor: #6C5CE7;\n\n<!-- HTML -->\n<a href=\"#section1\">セクション1へ</a>",
  },
  {
    id: "sym-arrow",
    term: "=>",
    reading: "アロー / ファットアロー",
    category: "symbol",
    shortDesc: "アロー関数の記法",
    detail: "JavaScript ES6で導入されたアロー関数の記法です。function キーワードの代わりに使い、より短く書けます。引数が1つなら()も省略可能です。thisの扱いが通常の関数と異なります。",
    example: "// 通常\nfunction add(a, b) { return a + b; }\n\n// アロー関数\nconst add = (a, b) => a + b;\n\n// 引数1つ\nconst double = x => x * 2;",
  },
  {
    id: "sym-template-literal",
    term: "` ` (バッククォート)",
    reading: "テンプレートリテラル",
    category: "symbol",
    shortDesc: "変数を埋め込める文字列",
    detail: "バッククォート(`)で囲んだ文字列はテンプレートリテラルと呼ばれ、${式} で変数や式を埋め込めます。改行もそのまま含められます。通常のクォート(' \")では変数の埋め込みはできません。",
    example: "const name = \"太郎\";\nconst age = 25;\n\n// テンプレートリテラル\nconst msg = `${name}さんは${age}歳です`;\n// → \"太郎さんは25歳です\"",
  },
  {
    id: "sym-triple-equals",
    term: "===",
    reading: "厳密等価演算子",
    category: "symbol",
    shortDesc: "型も含めて等しいかチェック",
    detail: "===は値と型の両方が等しいかを比較します。==（等価演算子）は型変換を行うため予期しない結果になることがあります。常に===を使うのが推奨されます。",
    example: '1 === 1     // true\n1 === "1"   // false（型が違う）\n1 == "1"    // true（==は型変換する）\nnull === undefined // false',
  },

  // ---- 一般 ----
  {
    id: "gen-api",
    term: "API",
    reading: "エーピーアイ",
    category: "general",
    shortDesc: "ソフトウェア間のデータやり取りの仕組み",
    detail: "API（Application Programming Interface）はソフトウェア同士がデータをやり取りするための窓口です。Web APIではHTTPリクエストを送ってサーバーからデータを取得します。fetch()やaxiosで利用します。",
    example: "// Web APIからデータ取得\nconst res = await fetch(\"https://api.example.com/data\");\nconst data = await res.json();",
  },
  {
    id: "gen-responsive",
    term: "レスポンシブデザイン",
    category: "general",
    shortDesc: "画面サイズに応じてレイアウトが変わる設計",
    detail: "レスポンシブデザインは、PC・タブレット・スマートフォンなど異なる画面サイズで最適に表示されるようにWebサイトを設計する手法です。CSSのメディアクエリ、Flexbox、相対単位(%、rem)を使って実現します。",
  },
  {
    id: "gen-framework",
    term: "フレームワーク",
    category: "general",
    shortDesc: "開発を効率化するための枠組み",
    detail: "フレームワークはよく使う機能や設計パターンをまとめた枠組みです。React、Vue、Angularなどのフロントエンドフレームワークや、Express、Next.jsなどのバックエンドフレームワークがあります。自分で1から作る部分を減らし、開発を効率化します。",
  },
  {
    id: "gen-debug",
    term: "デバッグ",
    category: "general",
    shortDesc: "プログラムのバグ（不具合）を見つけて修正すること",
    detail: "デバッグはコードの誤り（バグ）を特定して修正するプロセスです。console.log()で値を確認したり、ブラウザの開発者ツール（F12）のデバッガーを使ってステップ実行したりします。プログラマーの時間の大部分はデバッグに費やされます。",
    example: "// デバッグの基本\nconsole.log(\"ここまで来た\");\nconsole.log(\"変数の値:\", myVar);",
  },
];
