export interface GlossaryTerm {
  term: string;
  reading?: string;
  description: string;
  category: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // ── 基礎 ────────────────────────────────────────────────────────────────────
  {
    term: "インタプリタ",
    reading: "いんたぷりた",
    description: "ソースコードを1行ずつ読み込んで即座に実行するプログラム。Pythonはインタプリタ型言語であり、コンパイルなしにスクリプトを直接実行できる。",
    category: "基礎",
  },
  {
    term: "変数",
    reading: "へんすう",
    description: "データを格納するための名前付きの記憶領域。Pythonでは宣言不要で代入するだけで変数が作られ、型は動的に決定される。",
    category: "基礎",
  },
  {
    term: "動的型付け",
    reading: "どうてきかたつけ",
    description: "実行時に変数の型が決定される仕組み。Pythonは動的型付け言語であるため、同じ変数に異なる型の値を再代入できる。",
    category: "基礎",
  },
  {
    term: "インデント",
    reading: "いんでんと",
    description: "コードの字下げのこと。Pythonではインデントがコードブロックの区切りを意味し、スペース4つ（または一貫したタブ）が推奨される。",
    category: "基礎",
  },
  {
    term: "None",
    reading: "のーん",
    description: "「値が存在しない」ことを表すPython固有のオブジェクト。NullやNilに相当し、型はNoneType。関数が明示的に値を返さない場合も自動的にNoneが返される。",
    category: "基礎",
  },
  {
    term: "ミュータブル",
    reading: "みゅーたぶる",
    description: "作成後に内容を変更できるオブジェクトの性質。リスト・辞書・集合はミュータブルであり、要素の追加・削除・変更が可能。",
    category: "基礎",
  },
  {
    term: "イミュータブル",
    reading: "いみゅーたぶる",
    description: "作成後に内容を変更できないオブジェクトの性質。文字列・タプル・数値・frozensetはイミュータブルであり、辞書のキーとして使用できる。",
    category: "基礎",
  },
  {
    term: "PEP 8",
    reading: "ぺっぷえいと",
    description: "PEP（Python Enhancement Proposal）のうちコーディングスタイルを定めた標準ガイド。インデント・命名規則・行の長さなどのベストプラクティスが記述されている。",
    category: "基礎",
  },
  {
    term: "docstring",
    reading: "どっくすとりんぐ",
    description: "関数・クラス・モジュールの先頭に書くトリプルクォートの文字列。help()やIDEがドキュメントとして利用する。\"\"\"〜\"\"\" で囲む。",
    category: "基礎",
  },
  {
    term: "f文字列",
    reading: "えふもじれつ",
    description: "Python 3.6以降で使えるフォーマット済み文字列リテラル。f\"Hello, {name}!\" のように波括弧内に式を埋め込める。format()より簡潔で高速。",
    category: "基礎",
  },
  {
    term: "型変換",
    reading: "かたへんかん",
    description: "int()・str()・float()・list()などの組み込み関数を使って、ある型から別の型に値を変換すること。明示的キャストともいう。",
    category: "基礎",
  },
  {
    term: "スコープ",
    reading: "すこーぷ",
    description: "変数が参照できる有効範囲のこと。PythonはLEGBルール（Local → Enclosing → Global → Built-in）の順で名前を探索する。",
    category: "基礎",
  },
  {
    term: "グローバル変数",
    reading: "ぐろーばるへんすう",
    description: "モジュールのトップレベルで定義された変数。関数内から参照は可能だが、書き換えるにはglobalキーワードが必要。",
    category: "基礎",
  },
  {
    term: "ローカル変数",
    reading: "ろーかるへんすう",
    description: "関数内で定義された変数。その関数のスコープ内でのみ有効で、関数の外からはアクセスできない。",
    category: "基礎",
  },
  {
    term: "アンパック",
    reading: "あんぱっく",
    description: "タプル・リストなどのシーケンスの要素を複数の変数に同時に代入すること。a, b = 1, 2 や *rest を使った拡張アンパックも可能。",
    category: "基礎",
  },
  // ── データ構造 ────────────────────────────────────────────────────────────
  {
    term: "リスト",
    reading: "りすと",
    description: "順序を持つミュータブルなシーケンス。[1, 2, 3] のように角括弧で定義し、要素の追加・削除・並べ替えが可能。Pythonで最もよく使われるコレクション。",
    category: "データ構造",
  },
  {
    term: "タプル",
    reading: "たぷる",
    description: "順序を持つイミュータブルなシーケンス。(1, 2, 3) のように丸括弧で定義する。変更不要なデータの格納や辞書のキーに適している。",
    category: "データ構造",
  },
  {
    term: "辞書",
    reading: "じしょ",
    description: "キーと値のペアを格納するミュータブルなデータ構造。{\"key\": \"value\"} の形式で定義し、キーによる高速なアクセスが可能。Python 3.7以降は挿入順を保持する。",
    category: "データ構造",
  },
  {
    term: "集合（set）",
    reading: "しゅうごう",
    description: "重複を許さず順序を持たないミュータブルなコレクション。{1, 2, 3} または set() で生成し、和集合・差集合・積集合などの集合演算が使える。",
    category: "データ構造",
  },
  {
    term: "frozenset",
    reading: "ふろーずんせっと",
    description: "イミュータブルな集合。setと同じく重複を持たないが変更できないため、辞書のキーや集合の要素として使用できる。",
    category: "データ構造",
  },
  {
    term: "スライス",
    reading: "すらいす",
    description: "リストや文字列などのシーケンスの一部を [start:stop:step] 記法で切り出す操作。負のインデックスや省略も可能で非常に柔軟。",
    category: "データ構造",
  },
  {
    term: "リスト内包表記",
    reading: "りすとないほうひょうき",
    description: "[式 for 変数 in イテラブル if 条件] の形式でリストを一行で生成する構文。forループより簡潔で実行速度も速い場合が多い。",
    category: "データ構造",
  },
  {
    term: "辞書内包表記",
    reading: "じしょないほうひょうき",
    description: "{キー: 値 for 変数 in イテラブル} の形式で辞書を一行で生成する構文。",
    category: "データ構造",
  },
  {
    term: "イテラブル",
    reading: "いてらぶる",
    description: "forループで反復できるオブジェクト。リスト・タプル・文字列・辞書・ジェネレータなどが該当し、__iter__メソッドを持つ。",
    category: "データ構造",
  },
  {
    term: "イテレータ",
    reading: "いてれーた",
    description: "__next__()メソッドを持ち、要素を一つずつ返すオブジェクト。iter()でイテラブルから生成でき、StopIteration例外で終了を通知する。",
    category: "データ構造",
  },
  {
    term: "ジェネレータ",
    reading: "じぇねれーた",
    description: "yieldを使って値を逐次生成する関数。リスト全体をメモリに展開せず必要な分だけ生成するため、大量データ処理でメモリ効率が高い。",
    category: "データ構造",
  },
  {
    term: "deque",
    reading: "でく",
    description: "collectionsモジュールの両端キュー。先頭・末尾への追加・削除がO(1)で行えるため、キューやスタックの実装に適している。",
    category: "データ構造",
  },
  {
    term: "Counter",
    reading: "かうんたー",
    description: "collectionsモジュールのクラス。リストや文字列の各要素の出現回数を辞書形式で集計する。most_common()で頻度順の要素を取得できる。",
    category: "データ構造",
  },
  {
    term: "defaultdict",
    reading: "でふぉるとでぃくと",
    description: "collectionsモジュールの辞書サブクラス。存在しないキーへアクセスした際に自動でデフォルト値を生成するため、KeyErrorを回避できる。",
    category: "データ構造",
  },
  // ── OOP ──────────────────────────────────────────────────────────────────────
  {
    term: "クラス",
    reading: "くらす",
    description: "オブジェクトの設計図。データ（属性）と処理（メソッド）をひとまとめにした型を定義する。classキーワードで宣言する。",
    category: "OOP",
  },
  {
    term: "インスタンス",
    reading: "いんすたんす",
    description: "クラスから生成された具体的なオブジェクト。クラスを呼び出すことで生成され、それぞれ独立した属性を持つ。",
    category: "OOP",
  },
  {
    term: "コンストラクタ",
    reading: "こんすとらくた",
    description: "インスタンス生成時に自動で呼ばれる初期化メソッド。Pythonでは__init__がコンストラクタに相当し、selfと必要な引数を受け取る。",
    category: "OOP",
  },
  {
    term: "self",
    reading: "せるふ",
    description: "インスタンスメソッドの第1引数として渡されるインスタンス自身への参照。self.nameのようにインスタンス属性にアクセスするために使う。",
    category: "OOP",
  },
  {
    term: "継承",
    reading: "けいしょう",
    description: "既存のクラス（親クラス）の属性とメソッドを引き継いだ新しいクラス（子クラス）を定義する仕組み。class Child(Parent): の形式で記述する。",
    category: "OOP",
  },
  {
    term: "ポリモーフィズム",
    reading: "ぽりもーふぃずむ",
    description: "同じインターフェースで異なる型のオブジェクトを扱える性質。Pythonはダックタイピングによりポリモーフィズムを自然に実現する。",
    category: "OOP",
  },
  {
    term: "カプセル化",
    reading: "かぷせるか",
    description: "オブジェクトの内部状態を外部から隠蔽する考え方。Pythonでは_（慣習的な内部使用）や__（名前マングリング）で表現する。",
    category: "OOP",
  },
  {
    term: "抽象クラス",
    reading: "ちゅうしょうくらす",
    description: "インスタンス化できないクラスで、サブクラスに実装を強制するメソッドの定義に使う。ABCクラスと@abstractmethodデコレータを組み合わせる。",
    category: "OOP",
  },
  {
    term: "マジックメソッド",
    reading: "まじっくめそっど",
    description: "__init__・__str__・__len__・__add__など、アンダースコア2つで囲まれた特殊メソッド。Pythonの組み込み演算子や関数の振る舞いをカスタマイズできる。",
    category: "OOP",
  },
  {
    term: "プロパティ",
    reading: "ぷろぱてぃ",
    description: "@propertyデコレータで定義したメソッドを属性のようにアクセスさせる仕組み。セッター(@name.setter)を組み合わせて値の検証もできる。",
    category: "OOP",
  },
  {
    term: "データクラス",
    reading: "でーたくらす",
    description: "@dataclassデコレータを付けると__init__・__repr__・__eq__などが自動生成されるクラス。データ保持目的のクラスを簡潔に書ける。",
    category: "OOP",
  },
  {
    term: "メタクラス",
    reading: "めたくらす",
    description: "クラスを生成するクラス。Pythonではすべてのクラスはtypeのインスタンスであり、メタクラスをカスタマイズすることでクラスの生成過程を制御できる。",
    category: "OOP",
  },
  {
    term: "多重継承",
    reading: "たじゅうけいしょう",
    description: "複数の親クラスを同時に継承すること。Pythonではclass C(A, B): の形式で可能。名前の競合はMROによるC3線形化で解決する。",
    category: "OOP",
  },
  // ── モジュール ────────────────────────────────────────────────────────────────
  {
    term: "モジュール",
    reading: "もじゅーる",
    description: "Pythonのコードが格納された.pyファイル。importで読み込み、ファイル内の関数・クラス・変数を再利用できる。",
    category: "モジュール",
  },
  {
    term: "パッケージ",
    reading: "ぱっけーじ",
    description: "複数のモジュールをディレクトリでまとめたもの。__init__.pyを置くことでPythonパッケージとして認識される（Python 3.3以降は省略可能な場合もある）。",
    category: "モジュール",
  },
  {
    term: "pip",
    reading: "ぴっぷ",
    description: "Pythonの標準パッケージマネージャ。PyPIからサードパーティパッケージをインストール・管理する。pip install パッケージ名 で使用する。",
    category: "モジュール",
  },
  {
    term: "仮想環境",
    reading: "かそうかんきょう",
    description: "プロジェクトごとに独立したPython環境を作る仕組み。venvやPoetryで作成し、依存パッケージの競合を防ぎ再現性を確保する。",
    category: "モジュール",
  },
  {
    term: "venv",
    reading: "ぶいえんぶ",
    description: "Python標準の仮想環境作成モジュール。python -m venv .venv で仮想環境を作成し、activateスクリプトで有効化する。",
    category: "モジュール",
  },
  {
    term: "Poetry",
    reading: "ぽえとりー",
    description: "依存関係管理とパッケージ公開を統合したツール。pyproject.tomlで依存を管理し、poetry.lockで再現性を担保する。",
    category: "モジュール",
  },
  {
    term: "requirements.txt",
    reading: "りくわいあめんつてきすと",
    description: "プロジェクトの依存パッケージとバージョンを列挙したファイル。pip install -r requirements.txt で同じ環境を再現できる。",
    category: "モジュール",
  },
  {
    term: "PyPI",
    reading: "ぱいぴーあい",
    description: "Python Package Indexの略。Pythonのサードパーティパッケージを公開・配布するための公式リポジトリ。pipのデフォルトインストール元。",
    category: "モジュール",
  },
  {
    term: "デコレータ",
    reading: "でこれーた",
    description: "関数やクラスに機能を追加するためのシンタックスシュガー。@decorator_name の形式で使い、ロギング・認証・キャッシュなどの横断的関心事に活用する。",
    category: "モジュール",
  },
  {
    term: "ラムダ式",
    reading: "らむだしき",
    description: "lambda 引数: 式 の形式で書く無名関数。単純な処理を引数として渡すときに便利だが、複雑なロジックには通常のdefを推奨する。",
    category: "モジュール",
  },
  {
    term: "*args",
    reading: "あすたりすくあーぐす",
    description: "関数が任意の数の位置引数を受け取るための記法。関数内ではタプルとして扱われる。def f(*args): で定義する。",
    category: "モジュール",
  },
  {
    term: "**kwargs",
    reading: "だぶるあすたりすくかわーぐす",
    description: "関数が任意の数のキーワード引数を受け取るための記法。関数内では辞書として扱われる。def f(**kwargs): で定義する。",
    category: "モジュール",
  },
  {
    term: "例外処理",
    reading: "れいがいしょり",
    description: "try-except-else-finally構文を使ったエラーハンドリング。予期されるエラーを捕捉して適切に対処し、プログラムのクラッシュを防ぐ。",
    category: "モジュール",
  },
  {
    term: "コンテキストマネージャ",
    reading: "こんてきすとまねーじゃ",
    description: "with文で使えるオブジェクト。__enter__と__exit__メソッドを持ち、ファイルのオープン/クローズやDBトランザクションなどリソース管理を安全に行う。",
    category: "モジュール",
  },
  // ── Web ────────────────────────────────────────────────────────────────────
  {
    term: "Flask",
    reading: "ふらすく",
    description: "軽量なPython製Webフレームワーク。マイクロフレームワークと呼ばれ最小限の機能を提供し、拡張機能で機能を追加する設計思想を持つ。",
    category: "Web",
  },
  {
    term: "FastAPI",
    reading: "ふぁすとえーぴーあい",
    description: "型ヒントベースの高性能Python製APIフレームワーク。Pydanticによる自動バリデーション・Swagger UIの自動生成・非同期処理対応が特徴。",
    category: "Web",
  },
  {
    term: "Django",
    reading: "じゃんご",
    description: "フルスタックのPython製Webフレームワーク。ORM・テンプレートエンジン・管理画面・認証などが標準搭載され「バッテリー付属」と称される。",
    category: "Web",
  },
  {
    term: "WSGI",
    reading: "うぃずぎー",
    description: "Web Server Gateway Interfaceの略。PythonのWebアプリケーションとWebサーバーの間の標準インターフェース仕様。Flaskはこれに準拠している。",
    category: "Web",
  },
  {
    term: "ASGI",
    reading: "あすぎー",
    description: "Asynchronous Server Gateway Interfaceの略。WSGIの非同期版で、WebSocketやHTTP/2を含む非同期処理に対応する。FastAPIはASGIフレームワーク。",
    category: "Web",
  },
  {
    term: "Pydantic",
    reading: "ぱいだんてぃっく",
    description: "Pythonの型ヒントを使ったデータバリデーションライブラリ。BaseModelを継承したクラスを定義するだけで入力チェックとシリアライズが行える。",
    category: "Web",
  },
  {
    term: "Jinja2",
    reading: "じんじゃつー",
    description: "FlaskやDjangoで使われるPython製テンプレートエンジン。{{ 変数 }}・{% for %}・{% if %}などの構文でHTMLに動的データを埋め込む。",
    category: "Web",
  },
  {
    term: "ORM",
    reading: "おーあーるえむ",
    description: "Object-Relational Mappingの略。SQLを直接書かずPythonオブジェクトを操作するだけでDBとやりとりできる仕組み。DjangoのモデルやSQLAlchemyが有名。",
    category: "Web",
  },
  {
    term: "REST API",
    reading: "れすとえーぴーあい",
    description: "HTTPメソッド（GET・POST・PUT・DELETE）とURLでリソースを操作するWebAPIの設計様式。JSONを返すAPIを指すことが多い。",
    category: "Web",
  },
  // ── データサイエンス ─────────────────────────────────────────────────────────
  {
    term: "NumPy",
    reading: "なむぱい",
    description: "Pythonの数値計算ライブラリ。多次元配列（ndarray）と高速なベクトル演算を提供し、科学技術計算・機械学習の基盤となっている。",
    category: "データサイエンス",
  },
  {
    term: "Pandas",
    reading: "ぱんだす",
    description: "表形式データの操作・分析ライブラリ。DataFrame・Seriesという構造でCSVやJSON等のデータを読み込み、集計・変換・可視化を行える。",
    category: "データサイエンス",
  },
  {
    term: "Matplotlib",
    reading: "まっとぷろっとりぶ",
    description: "Pythonのデータ可視化ライブラリ。折れ線・棒・散布図・ヒストグラムなど多様なグラフを描画でき、科学論文品質の出力にも対応する。",
    category: "データサイエンス",
  },
  {
    term: "DataFrame",
    reading: "でーたふれーむ",
    description: "Pandasの2次元の表形式データ構造。行と列にラベルを持ち、Excelのスプレッドシートに近い感覚でデータを操作できる。",
    category: "データサイエンス",
  },
  {
    term: "Series",
    reading: "しりーず",
    description: "Pandasの1次元のラベル付き配列。DataFrameの1列を取り出したものに相当し、インデックスによる高速なアクセスが可能。",
    category: "データサイエンス",
  },
  {
    term: "ブロードキャスト",
    reading: "ぶろーどきゃすと",
    description: "NumPyで形状の異なる配列を演算する際に、小さい配列を自動的に拡張して合わせる仕組み。明示的にコピーを作らないためメモリ効率が良い。",
    category: "データサイエンス",
  },
  {
    term: "ndarray",
    reading: "えんでぃあれい",
    description: "NumPyの多次元配列クラス。均一な型の要素を格納し、C言語レベルの高速計算を実現する。.shapeや.dtypeで形状・型を確認できる。",
    category: "データサイエンス",
  },
  // ── テスト ────────────────────────────────────────────────────────────────────
  {
    term: "pytest",
    reading: "ぱいてすと",
    description: "Pythonの人気テストフレームワーク。シンプルなassert文でテストを書けるうえ、豊富なプラグインエコシステムを持つ。",
    category: "テスト",
  },
  {
    term: "フィクスチャ",
    reading: "ふぃくすちゃ",
    description: "pytestの@pytest.fixtureで定義するテストの前準備・後処理の共有機能。依存注入の形式で各テスト関数に自動提供される。",
    category: "テスト",
  },
  {
    term: "モック",
    reading: "もっく",
    description: "テスト時に外部API・DBなどの依存を置き換える偽オブジェクト。unittest.mockモジュールのMockやMagicMockを使って動作を制御・検証する。",
    category: "テスト",
  },
  {
    term: "パラメータ化テスト",
    reading: "ぱらめーたかてすと",
    description: "@pytest.mark.parametrizeデコレータを使い、複数の入力パターンを1つのテスト関数でまとめて検証する手法。",
    category: "テスト",
  },
  {
    term: "TDD",
    reading: "てぃーでぃーでぃー",
    description: "テスト駆動開発（Test-Driven Development）の略。テストを先に書き、そのテストをパスするコードを実装するサイクルで開発する手法。",
    category: "テスト",
  },
  {
    term: "カバレッジ",
    reading: "かばれっじ",
    description: "テストによってどれだけのコードが実行されたかを示す指標。pytest-covプラグインで計測し、未テストのコードパスを特定する。",
    category: "テスト",
  },
  // ── 応用 ─────────────────────────────────────────────────────────────────────
  {
    term: "asyncio",
    reading: "えいしんくあいおー",
    description: "Pythonの非同期I/O処理を行う標準ライブラリ。イベントループを使ってコルーチンを協調的に実行し、I/O待ち時間を効率的に利用する。",
    category: "応用",
  },
  {
    term: "コルーチン",
    reading: "こるーちん",
    description: "async defで定義した非同期関数。awaitで一時停止・再開でき、複数のタスクを非同期に実行するasyncioの基本単位。",
    category: "応用",
  },
  {
    term: "GIL",
    reading: "じーあいえる",
    description: "Global Interpreter Lockの略。CPythonで同時に実行できるPythonバイトコードは1スレッドのみに制限するロック機構。CPUバウンドな処理はマルチプロセスが有効。",
    category: "応用",
  },
  {
    term: "型ヒント",
    reading: "かたひんと",
    description: "変数・引数・戻り値に型情報を注釈として付与する機能（Python 3.5以降）。実行時チェックではなくIDEや静的解析ツール（mypy等）が利用する。",
    category: "応用",
  },
  {
    term: "Protocol",
    reading: "ぷろとこる",
    description: "typingモジュールのクラス。特定のメソッドや属性を持つという構造的サブタイピング（ダックタイピングの型版）を表現するために使う。",
    category: "応用",
  },
  {
    term: "TypeVar",
    reading: "たいぷばー",
    description: "typing.TypeVarで定義するジェネリックな型変数。型ヒントで任意の型を受け付ける汎用関数やクラスを定義する際に使う。",
    category: "応用",
  },
  {
    term: "正規表現",
    reading: "せいきひょうげん",
    description: "文字列のパターンを表す記法。Pythonではreモジュールを使い、メタ文字・文字クラス・繰り返し記号などで検索・置換・分割が行える。",
    category: "応用",
  },
  {
    term: "ロギング",
    reading: "ろぎんぐ",
    description: "loggingモジュールを使ったアプリの動作記録。DEBUG・INFO・WARNING・ERROR・CRITICALのレベルで重要度を分類し、ファイルや標準出力に出力する。",
    category: "応用",
  },
  {
    term: "SOLID原則",
    reading: "そりっどげんそく",
    description: "オブジェクト指向設計の5原則（単一責任・開放閉鎖・リスコフ置換・インターフェース分離・依存性逆転）の頭文字。保守性・拡張性の高いコードの指針。",
    category: "応用",
  },
  {
    term: "デザインパターン",
    reading: "でざいんぱたーん",
    description: "ソフトウェア設計でよく使われる問題解決の定型解。GoFパターン（生成・構造・振る舞いの3分類23パターン）が有名で、PythonでもFactory・Observerなどが使われる。",
    category: "応用",
  },
  {
    term: "プロファイリング",
    reading: "ぷろふぁいりんぐ",
    description: "プログラムのどの部分が実行時間やメモリを多く消費しているかを計測する作業。cProfileやtimeitモジュール、line_profilerなどを使う。",
    category: "応用",
  },
  {
    term: "ダックタイピング",
    reading: "だっくたいぴんぐ",
    description: "「アヒルのように歩きアヒルのように鳴くなら、それはアヒルだ」という考え方。Pythonでは型を明示的に確認せず、必要なメソッドや属性を持つかどうかで判断する。",
    category: "応用",
  },
  {
    term: "MRO",
    reading: "えむあーるおー",
    description: "Method Resolution Orderの略。多重継承時にメソッドを検索する順序。PythonはC3線形化アルゴリズムで決定し、ClassName.__mro__で確認できる。",
    category: "応用",
  },
];
