export interface GlossaryTerm {
  term: string;
  reading?: string;
  description: string;
  category: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // ── 基礎 ────────────────────────────────────────────────────────────────────
  {
    term: "val",
    reading: "う゛ぁる",
    description: "再代入不可の変数（イミュータブル）を宣言するキーワード。Javaの final に相当する。一度値を設定すると変更できない。定数や変化しない参照には val を使うことが推奨される。",
    category: "基礎",
  },
  {
    term: "var",
    reading: "う゛ぁー",
    description: "再代入可能な変数（ミュータブル）を宣言するキーワード。値の変更が可能。val で宣言できる場合は val を使うことが推奨される。",
    category: "基礎",
  },
  {
    term: "fun",
    reading: "ふぁん",
    description: "関数を定義するキーワード。`fun 関数名(引数): 戻り値の型 { ... }` の形式で宣言する。戻り値がない場合は Unit（省略可）を返す。",
    category: "基礎",
  },
  {
    term: "Unit",
    reading: "ゆにっと",
    description: "値を返さないことを示す型。Javaの void に相当するが、Unit は実際に値（Unitオブジェクト）を返す型。関数の戻り値型として通常は省略できる。",
    category: "基礎",
  },
  {
    term: "String テンプレート",
    reading: "すとりんぐてんぷれーと",
    description: "文字列の中に変数や式を埋め込む機能。`$変数名` または `${式}` の形式で使う。例: `\"Hello, $name!\"`。文字列連結より読みやすく記述できる。",
    category: "基礎",
  },
  {
    term: "型推論",
    reading: "かたすいろん",
    description: "変数宣言時に型を省略してもコンパイラが自動で型を決定する機能。`val x = 42` では x が Int と推論される。明示的に型を書く必要がない場面が多い。",
    category: "基礎",
  },
  {
    term: "null安全",
    reading: "なるあんぜん",
    description: "Kotlinの重要な特徴。変数はデフォルトで null を格納できず、null を許可するには型に ? を付ける（例: String?）。NullPointerException を防ぐ設計になっている。",
    category: "基礎",
  },
  {
    term: "?.",
    reading: "せーふこーる",
    description: "セーフコール演算子。オブジェクトが null でない場合のみメソッドやプロパティにアクセスし、null の場合は null を返す。例: `str?.length`。",
    category: "基礎",
  },
  {
    term: "?:",
    reading: "えるびすえんざんし",
    description: "エルビス演算子。左辺が null の場合に右辺の値を返す。例: `val name = str ?: \"デフォルト\"`。Javaの三項演算子の null チェックに相当する。",
    category: "基礎",
  },
  {
    term: "!!",
    reading: "のんなるあさーしょん",
    description: "非null表明演算子。値が null でないことをコンパイラに強制的に主張する。null の場合は KotlinNullPointerException が発生する。使用は最小限にすべき。",
    category: "基礎",
  },
  {
    term: "lateinit",
    reading: "れいといにっと",
    description: "var プロパティの初期化を後回しにするキーワード。非null型でも宣言時に初期化しなくてよい。初期化前にアクセスすると UninitializedPropertyAccessException が発生する。",
    category: "基礎",
  },
  {
    term: "lazy",
    reading: "れいじー",
    description: "プロパティを初めてアクセスした時点で初期化する委譲プロパティ。`val x by lazy { 計算処理 }` の形式で使う。val にのみ使用可能でスレッドセーフ。",
    category: "基礎",
  },
  {
    term: "Any",
    reading: "えにー",
    description: "Kotlinのすべてのクラスのスーパークラス。Javaの Object に相当する。toString()、equals()、hashCode() メソッドを持つ。",
    category: "基礎",
  },
  {
    term: "Nothing",
    reading: "なっしんぐ",
    description: "値を返さない（正常に完了しない）関数の戻り値型。例外を必ずスローする関数に使う。サブタイプ推論や無限ループにも使用される。",
    category: "基礎",
  },
  {
    term: "typealias",
    reading: "たいぷえいりあす",
    description: "既存の型に別名をつけるキーワード。`typealias StringList = List<String>` のように定義する。コードの可読性を高めるために使う。新しい型は作成しない。",
    category: "基礎",
  },
  {
    term: "when",
    reading: "うぇん",
    description: "Kotlinの多分岐条件式・文。Javaの switch に相当するが大幅に強化されており、任意の型や条件でパターンマッチングができる。値を返す式としても使える。",
    category: "基礎",
  },
  {
    term: "範囲演算子",
    reading: "はんいえんざんし",
    description: "`..` で範囲を生成する演算子。`1..10` は1から10の範囲。`until` は終端を含まない。`downTo` で降順、`step` でステップ数を指定できる。",
    category: "基礎",
  },
  {
    term: "println",
    reading: "ぷりんとれん",
    description: "標準出力に値を出力し改行する関数。`print` は改行なし。文字列テンプレートと組み合わせて `println(\"Hello, $name!\")` のように使う。",
    category: "基礎",
  },
  // ── OOP ──────────────────────────────────────────────────────────────────
  {
    term: "class",
    reading: "くらす",
    description: "クラスを定義するキーワード。Kotlinのクラスはデフォルトで final（継承不可）。継承を許可するには open キーワードが必要。プライマリコンストラクタをヘッダに書ける。",
    category: "OOP",
  },
  {
    term: "data class",
    reading: "でーたくらす",
    description: "データを保持するためのクラス。equals()、hashCode()、toString()、copy()、componentN() メソッドが自動生成される。コンストラクタのプロパティがデータとして扱われる。",
    category: "OOP",
  },
  {
    term: "sealed class",
    reading: "しーるどくらす",
    description: "継承できるサブクラスを同じファイル（またはパッケージ）内に限定するクラス。when 式と組み合わせて網羅的なパターンマッチングが可能。代数的データ型の表現に使う。",
    category: "OOP",
  },
  {
    term: "object",
    reading: "おぶじぇくと",
    description: "シングルトンを定義するキーワード。インスタンスが1つだけ生成される。`object MySingleton { ... }` の形式で宣言し、クラス名でそのまま直接アクセスできる。",
    category: "OOP",
  },
  {
    term: "companion object",
    reading: "こんぱにおんおぶじぇくと",
    description: "クラス内に定義するシングルトンオブジェクト。Javaの static メンバに相当する。クラス名から直接アクセスできる。ファクトリメソッドの定義によく使われる。",
    category: "OOP",
  },
  {
    term: "open",
    reading: "おーぷん",
    description: "クラスやメソッドを継承・オーバーライド可能にするキーワード。Kotlinのクラスはデフォルトで final なので、継承を許可するには明示的に open が必要。",
    category: "OOP",
  },
  {
    term: "override",
    reading: "おーばーらいど",
    description: "親クラスやインターフェースのメソッド・プロパティをオーバーライドするキーワード。Javaの @Override アノテーションと異なり、Kotlinでは必須のキーワード。",
    category: "OOP",
  },
  {
    term: "abstract",
    reading: "あぶすとらくと",
    description: "抽象クラスまたは抽象メソッドを宣言するキーワード。抽象クラスはインスタンス化できず、サブクラスに実装を強制する。abstract クラスは自動的に open でもある。",
    category: "OOP",
  },
  {
    term: "interface",
    reading: "いんたーふぇーす",
    description: "インターフェースを定義するキーワード。デフォルト実装を持つことができる。プロパティも宣言できる（バッキングフィールドは持てない）。複数のインターフェースを実装可能。",
    category: "OOP",
  },
  {
    term: "value class",
    reading: "う゛ぁりゅーくらす",
    description: "単一のプロパティをラップする軽量クラス。実行時にはプロパティの型そのものとして扱われる（ボックス化回避）。型安全なラッパーを効率的に実装できる。",
    category: "OOP",
  },
  {
    term: "プロパティ",
    reading: "ぷろぱてぃ",
    description: "クラスのデータを表すフィールドとアクセサ（getter/setter）を組み合わせた概念。`val/var プロパティ名: 型` で宣言し、カスタムアクセサも定義できる。",
    category: "OOP",
  },
  {
    term: "継承",
    reading: "けいしょう",
    description: "既存クラスの機能を引き継いで新しいクラスを作る仕組み。`: 親クラス()` の形式で指定する。Kotlinは単一継承のみサポート。親クラスは open キーワードが必要。",
    category: "OOP",
  },
  {
    term: "ジェネリクス",
    reading: "じぇねりくす",
    description: "型パラメータを使って汎用的なクラスやメソッドを定義する仕組み。`List<String>` のように型安全なコレクションを実現する。out（共変）、in（反変）修飾子もサポート。",
    category: "OOP",
  },
  // ── コレクション ──────────────────────────────────────────────────────────
  {
    term: "listOf",
    reading: "りすとおぶ",
    description: "読み取り専用リストを生成する関数。`listOf(1, 2, 3)` のように使う。変更可能なリストは `mutableListOf()` を使う。Javaの List.of に相当する。",
    category: "コレクション",
  },
  {
    term: "mapOf",
    reading: "まっぷおぶ",
    description: "読み取り専用マップを生成する関数。`mapOf(\"key\" to value)` のように使う。変更可能なマップは `mutableMapOf()` を使う。`to` は infix 関数で Pair を作る。",
    category: "コレクション",
  },
  {
    term: "setOf",
    reading: "せっとおぶ",
    description: "重複なしの読み取り専用セットを生成する関数。`setOf(1, 2, 3)` のように使う。変更可能なセットは `mutableSetOf()` を使う。",
    category: "コレクション",
  },
  {
    term: "filter",
    reading: "ふぃるたー",
    description: "条件を満たす要素だけのリストを返す高階関数。`list.filter { it > 3 }` のように使う。元のコレクションは変更しない。",
    category: "コレクション",
  },
  {
    term: "map（変換）",
    reading: "まっぷ",
    description: "各要素を変換した新しいリストを返す高階関数。`list.map { it * 2 }` のように使う。コレクション型の Map とは別物。",
    category: "コレクション",
  },
  {
    term: "flatMap",
    reading: "ふらっとまっぷ",
    description: "各要素をコレクションに変換し、それらを結合して平坦化したリストを返す。ネストしたコレクションの処理によく使われる。",
    category: "コレクション",
  },
  {
    term: "fold / reduce",
    reading: "ふぉーるど / りでゅーす",
    description: "コレクションの要素を1つの値に畳み込む高階関数。`fold` は初期値を指定できる。`reduce` は初期値なし（空コレクションでは例外）。",
    category: "コレクション",
  },
  {
    term: "groupBy",
    reading: "ぐるーぷばい",
    description: "コレクションの要素をキーでグループ化し、`Map<K, List<V>>` を返す。`list.groupBy { it.category }` のようにカテゴリ別に分類するときに便利。",
    category: "コレクション",
  },
  {
    term: "sortedBy",
    reading: "そーてっどばい",
    description: "コレクションを特定のプロパティでソートした新しいリストを返す関数。`list.sortedBy { it.age }` のように使う。`sortedByDescending` で降順ソートも可能。",
    category: "コレクション",
  },
  {
    term: "Sequence",
    reading: "しーくえんす",
    description: "要素を遅延評価するコレクション。`asSequence()` で変換する。大きなデータセットや中間操作が多い場合にパフォーマンスが向上する。",
    category: "コレクション",
  },
  {
    term: "forEach",
    reading: "ふぉーいーち",
    description: "コレクションの各要素に対してラムダを実行する終端処理関数。`list.forEach { println(it) }` のように使う。戻り値は Unit。",
    category: "コレクション",
  },
  // ── 関数型 ──────────────────────────────────────────────────────────────────
  {
    term: "ラムダ式",
    reading: "らむだしき",
    description: "匿名関数を簡潔に記述する構文。`{ 引数 -> 処理 }` の形式。1引数の場合は `it` で暗黙参照できる。高階関数に渡す際に多用される。",
    category: "関数型",
  },
  {
    term: "高階関数",
    reading: "こうかいかんすう",
    description: "関数を引数として受け取ったり、関数を返したりする関数。Kotlinでは関数型 `(A) -> B` を型として使える。`filter`、`map`、`let` などが代表例。",
    category: "関数型",
  },
  {
    term: "拡張関数",
    reading: "かくちょうかんすう",
    description: "既存のクラスを継承せずにメソッドを追加する機能。`fun クラス名.関数名()` の形式で定義する。レシーバーオブジェクトに `this` でアクセスできる。",
    category: "関数型",
  },
  {
    term: "スコープ関数",
    reading: "すこーぷかんすう",
    description: "オブジェクトのスコープ内でコードを実行するための関数群。let、run、with、apply、also の5種類がある。オブジェクトの初期化・変換・副作用に便利。",
    category: "関数型",
  },
  {
    term: "let",
    reading: "れっと",
    description: "スコープ関数の1つ。`it` でオブジェクトを参照し、ブロックの最後の式を返す。null安全チェック（`obj?.let { }`）と組み合わせてよく使われる。",
    category: "関数型",
  },
  {
    term: "apply",
    reading: "あぷらい",
    description: "スコープ関数の1つ。`this` でオブジェクトを参照し、オブジェクト自身を返す。オブジェクトの初期化・設定に使う。`builder.apply { ... }` のように。",
    category: "関数型",
  },
  {
    term: "also",
    reading: "おーるそー",
    description: "スコープ関数の1つ。`it` でオブジェクトを参照し、オブジェクト自身を返す。副作用（ログ出力など）を行いながらチェーンを続けたい場合に使う。",
    category: "関数型",
  },
  {
    term: "run",
    reading: "らん",
    description: "スコープ関数の1つ。`this` でオブジェクトを参照し、ブロックの最後の式を返す。オブジェクトの設定と結果の計算を1つのブロックで行う場合に使う。",
    category: "関数型",
  },
  {
    term: "with",
    reading: "うぃず",
    description: "スコープ関数の1つ（拡張関数ではない）。`this` でオブジェクトを参照し、ブロックの最後の式を返す。non-nullのオブジェクトに対して複数の操作を行う場合に使う。",
    category: "関数型",
  },
  {
    term: "inline",
    reading: "いんらいん",
    description: "関数呼び出しをコンパイル時にインライン展開するキーワード。ラムダを受け取る高階関数に付けることで、実行時のオーバーヘッドを削減できる。",
    category: "関数型",
  },
  {
    term: "reified",
    reading: "りふぁいど",
    description: "inline 関数内で型パラメータを実行時に利用可能にするキーワード。`inline fun <reified T> ...` の形式で使い、`T::class` でクラス情報を取得できる。",
    category: "関数型",
  },
  // ── 非同期 ──────────────────────────────────────────────────────────────────
  {
    term: "コルーチン",
    reading: "こるーちん",
    description: "Kotlinの非同期処理の仕組み。スレッドよりも軽量で、suspend 関数を使って非同期コードを同期的なスタイルで書ける。kotlinx.coroutines ライブラリで提供される。",
    category: "非同期",
  },
  {
    term: "suspend",
    reading: "さすぺんど",
    description: "コルーチン内で一時停止できる関数を示すキーワード。suspend 関数はコルーチンまたは他の suspend 関数からのみ呼び出せる。スレッドをブロックしない。",
    category: "非同期",
  },
  {
    term: "launch",
    reading: "ろーんち",
    description: "新しいコルーチンを起動するビルダー。結果を返さない（Unit）場合に使う。`CoroutineScope.launch { }` の形式で呼び出す。Job を返す。",
    category: "非同期",
  },
  {
    term: "async",
    reading: "えいしんく",
    description: "結果を返すコルーチンビルダー。`Deferred<T>` を返し、`.await()` で結果を取得する。複数の非同期処理を並行実行してから結果をまとめるのに使う。",
    category: "非同期",
  },
  {
    term: "Flow",
    reading: "ふろー",
    description: "非同期ストリームを表す型。複数の値を逐次的に流すことができる。cold stream（収集するまで実行しない）。`collect { }` で値を受け取る。",
    category: "非同期",
  },
  {
    term: "StateFlow",
    reading: "すてーとふろー",
    description: "現在の状態を保持し、変更を通知するホットなフロー。UI の状態管理に使われる。常に最新の値を持ち、コレクタが接続するとすぐに現在の値を受信する。",
    category: "非同期",
  },
  {
    term: "CoroutineScope",
    reading: "こるーちんすこーぷ",
    description: "コルーチンのライフサイクルを管理するスコープ。このスコープ内で起動されたコルーチンはスコープがキャンセルされると一緒にキャンセルされる。",
    category: "非同期",
  },
  {
    term: "Dispatchers",
    reading: "でぃすぱっちゃーず",
    description: "コルーチンを実行するスレッドを指定するオブジェクト群。`Dispatchers.IO`（I/O処理）、`Dispatchers.Main`（メインスレッド）、`Dispatchers.Default`（CPU処理）がある。",
    category: "非同期",
  },
  {
    term: "withContext",
    reading: "うぃずこんてきすと",
    description: "コルーチンのコンテキスト（ディスパッチャなど）を切り替えてブロックを実行する関数。`withContext(Dispatchers.IO) { }` でI/O処理を行うのが典型的な使い方。",
    category: "非同期",
  },
  {
    term: "delay",
    reading: "でれい",
    description: "指定した時間（ミリ秒）だけコルーチンを一時停止する suspend 関数。スレッドをブロックしない。`delay(1000)` で1秒待機する。テストや非同期処理の調整に使う。",
    category: "非同期",
  },
  // ── ビルド ──────────────────────────────────────────────────────────────────
  {
    term: "Gradle",
    reading: "ぐれいどる",
    description: "KotlinおよびAndroid開発の標準ビルドツール。`build.gradle.kts`（Kotlin DSL）または `build.gradle`（Groovy DSL）で設定を記述する。",
    category: "ビルド",
  },
  {
    term: "build.gradle.kts",
    reading: "びるどぐれいどるけーてぃえす",
    description: "Kotlin DSLで記述するGradleビルドスクリプト。型安全で補完が効くため、`build.gradle`（Groovy）より推奨される。Kotlinそのものの構文で設定できる。",
    category: "ビルド",
  },
  {
    term: "dependencies",
    reading: "でぃぺんでんしーず",
    description: "Gradleで外部ライブラリへの依存を宣言するブロック。`implementation`（実装用）、`testImplementation`（テスト用）などのスコープで依存を追加する。",
    category: "ビルド",
  },
  {
    term: "JUnit",
    reading: "じぇいゆにっと",
    description: "JavaおよびKotlinで使われる標準テストフレームワーク。`@Test` アノテーションでテストメソッドを定義し、Kotlinのコードも同様にテストできる。",
    category: "ビルド",
  },
  {
    term: "kotlinx.serialization",
    reading: "ことりんえっくすしりあらいぜーしょん",
    description: "KotlinのマルチプラットフォームなJSONシリアライゼーションライブラリ。`@Serializable` アノテーションを付けるだけで data class をJSONと相互変換できる。",
    category: "ビルド",
  },
  {
    term: "Ktor",
    reading: "けーたー",
    description: "Kotlinで書かれた非同期Webフレームワーク。サーバーサイドおよびクライアントサイドの両方をサポート。コルーチンベースで軽量かつ高速に動作する。",
    category: "ビルド",
  },
  // ── Kotlin特有 ──────────────────────────────────────────────────────────────
  {
    term: "スマートキャスト",
    reading: "すまーときゃすと",
    description: "型チェックを行うと、その後のコードで自動的に型キャストが適用される機能。`if (obj is String) { obj.length }` のように、明示的なキャスト不要でアクセスできる。",
    category: "Kotlin特有",
  },
  {
    term: "is / !is",
    reading: "いず / のっといず",
    description: "型チェックを行う演算子。`obj is String` で true/false を返し、スマートキャストも自動で行われる。Javaの `instanceof` に相当する。",
    category: "Kotlin特有",
  },
  {
    term: "as / as?",
    reading: "えーえす / えーえすくえすちょん",
    description: "型キャスト演算子。`as` は変換失敗時に例外、`as?` は変換失敗時に null を返す安全なキャスト。`val str = obj as? String` のように使う。",
    category: "Kotlin特有",
  },
  {
    term: "by キーワード",
    reading: "ばいきーわーど",
    description: "委譲を表すキーワード。プロパティの委譲（`val x by lazy { }`）やインターフェースの委譲（`class A(b: B) : BInterface by b`）に使う。",
    category: "Kotlin特有",
  },
  {
    term: "演算子オーバーロード",
    reading: "えんざんしおーばーろーど",
    description: "+、-、*、/ などの演算子をカスタムクラスに対して定義できる機能。`operator fun plus(other: T): T` のように `operator` キーワードを付けて定義する。",
    category: "Kotlin特有",
  },
  {
    term: "デストラクチャリング",
    reading: "でするくちゃりんぐ",
    description: "オブジェクトの複数のプロパティを一度に変数に展開する機能。`val (a, b) = pair` のように使う。data class では componentN() が自動生成されてサポートされる。",
    category: "Kotlin特有",
  },
  {
    term: "in / !in",
    reading: "いん / のっといん",
    description: "コレクションや範囲に要素が含まれるかチェックする演算子。`if (x in 1..10)` や `if (name in list)` のように使う。for ループの範囲指定にも使う。",
    category: "Kotlin特有",
  },
  {
    term: "object式",
    reading: "おぶじぇくとしき",
    description: "匿名クラスのインスタンスを生成する構文。`object : Interface { ... }` の形式で使う。Javaの匿名クラスに相当するが、より簡潔に書ける。",
    category: "Kotlin特有",
  },
  {
    term: "infix関数",
    reading: "いんふぃっくすかんすう",
    description: "中置記法で呼び出せる関数を定義するキーワード。`infix fun` で定義し、`1 to 2` のように `obj func arg` の形式で呼べる。`mapOf` の `to` がその代表例。",
    category: "Kotlin特有",
  },
  {
    term: "tailrec",
    reading: "てーるれく",
    description: "末尾再帰を最適化するキーワード。`tailrec fun` で定義した関数は、コンパイラがループに変換してスタックオーバーフローを防ぐ。末尾での再帰呼び出しにのみ使える。",
    category: "Kotlin特有",
  },
];
