export interface GlossaryTerm {
  term: string;
  reading?: string;
  description: string;
  category: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // ── 基礎 ────────────────────────────────────────────────────────────────────
  {
    term: "変数",
    reading: "へんすう",
    description: "データを格納するための名前付きの記憶領域。C#では宣言時に型を指定するか、varキーワードで型推論を利用する。",
    category: "基礎",
  },
  {
    term: "型",
    reading: "かた",
    description: "変数やオブジェクトが保持するデータの種類を定義する仕組み。C#は静的型付け言語であり、コンパイル時に型チェックが行われる。",
    category: "基礎",
  },
  {
    term: "静的型付け",
    reading: "せいてきかたつけ",
    description: "コンパイル時に変数の型が決定される仕組み。C#は静的型付け言語であるため、型の不一致はコンパイルエラーとなる。",
    category: "基礎",
  },
  {
    term: "値型",
    reading: "あたいがた",
    description: "変数がデータそのものを直接保持する型。int・double・bool・struct・enumなどが値型に該当し、スタックに格納される。",
    category: "基礎",
  },
  {
    term: "参照型",
    reading: "さんしょうがた",
    description: "変数がデータへの参照（ポインタ）を保持する型。class・string・配列・delegateなどが参照型に該当し、ヒープに格納される。",
    category: "基礎",
  },
  {
    term: "名前空間",
    reading: "なまえくうかん",
    description: "関連するクラスや型をグループ化する仕組み。namespaceキーワードで定義し、usingディレクティブで参照する。",
    category: "基礎",
  },
  {
    term: "var",
    reading: "ばー",
    description: "暗黙的に型を推論するキーワード。右辺の値からコンパイラが自動的に型を決定する。動的型ではなくコンパイル時に型が確定する。",
    category: "基礎",
  },
  {
    term: "const",
    reading: "こんすと",
    description: "コンパイル時定数を宣言するキーワード。宣言時に値を初期化する必要があり、後から変更できない。",
    category: "基礎",
  },
  {
    term: "readonly",
    reading: "りーどおんりー",
    description: "実行時定数を宣言するキーワード。コンストラクタ内で初期化でき、一度設定された値は変更できない。",
    category: "基礎",
  },
  {
    term: "Nullable型",
    reading: "なるあぶるがた",
    description: "null値を許容する値型。int? のように型名の後に ? を付けて宣言する。null合体演算子(??)やnull条件演算子(?.)と組み合わせて使う。",
    category: "基礎",
  },
  {
    term: "型変換",
    reading: "かたへんかん",
    description: "ある型から別の型に値を変換すること。暗黙的変換（自動）と明示的変換（キャスト）があり、Convert クラスも利用できる。",
    category: "基礎",
  },
  {
    term: "演算子",
    reading: "えんざんし",
    description: "値に対して操作を行う記号。算術(+,-,*,/)・比較(==,!=,<,>)・論理(&&,||,!)・null合体(??)・null条件(?.)などがある。",
    category: "基礎",
  },
  {
    term: "文字列補間",
    reading: "もじれつほかん",
    description: "C# 6以降で使える文字列の埋め込み機能。$\"Hello, {name}!\" のようにドル記号と波括弧で式を埋め込める。",
    category: "基礎",
  },
  {
    term: "コメント",
    reading: "こめんと",
    description: "コード中の説明文。// で単一行、/* */ で複数行、/// でXMLドキュメントコメントを記述できる。",
    category: "基礎",
  },
  // ── データ構造 ────────────────────────────────────────────────────────────
  {
    term: "配列",
    reading: "はいれつ",
    description: "同じ型の要素を固定数格納するデータ構造。int[] arr = new int[5] のように宣言し、インデックスでアクセスする。サイズは変更不可。",
    category: "データ構造",
  },
  {
    term: "List<T>",
    reading: "りすと",
    description: "動的にサイズが変わるジェネリックコレクション。Add・Remove・Sort などのメソッドを持ち、配列よりも柔軟にデータを管理できる。",
    category: "データ構造",
  },
  {
    term: "Dictionary<TKey,TValue>",
    reading: "でぃくしょなりー",
    description: "キーと値のペアを格納するコレクション。キーによるO(1)の高速検索が可能。キーは一意でなければならない。",
    category: "データ構造",
  },
  {
    term: "HashSet<T>",
    reading: "はっしゅせっと",
    description: "重複を許さない要素の集合。Contains()がO(1)で動作し、集合演算（和・積・差）もサポートする。",
    category: "データ構造",
  },
  {
    term: "Queue<T>",
    reading: "きゅー",
    description: "先入れ先出し（FIFO）のデータ構造。Enqueue()で末尾に追加、Dequeue()で先頭から取り出す。",
    category: "データ構造",
  },
  {
    term: "Stack<T>",
    reading: "すたっく",
    description: "後入れ先出し（LIFO）のデータ構造。Push()で先頭に追加、Pop()で先頭から取り出す。",
    category: "データ構造",
  },
  {
    term: "LinkedList<T>",
    reading: "りんくどりすと",
    description: "双方向連結リスト。任意の位置への挿入・削除がO(1)で行えるが、インデックスアクセスはO(n)。",
    category: "データ構造",
  },
  {
    term: "Span<T>",
    reading: "すぱん",
    description: "配列やメモリの一部を効率的に参照する構造体。コピーなしでデータのスライスを扱え、パフォーマンス向上に貢献する。",
    category: "データ構造",
  },
  {
    term: "IEnumerable<T>",
    reading: "あいいにゅめらぶる",
    description: "foreachで反復可能なシーケンスを表すインターフェース。LINQの基盤となり、遅延実行をサポートする。",
    category: "データ構造",
  },
  {
    term: "StringBuilder",
    reading: "すとりんぐびるだー",
    description: "大量の文字列連結を効率的に行うためのクラス。stringは不変であるため、繰り返しの連結にはStringBuilderを使うべき。",
    category: "データ構造",
  },
  {
    term: "タプル",
    reading: "たぷる",
    description: "複数の値をひとまとめにする軽量なデータ構造。(int, string) tuple = (1, \"hello\") のように宣言する。名前付き要素も利用可能。",
    category: "データ構造",
  },
  {
    term: "Immutableコレクション",
    reading: "いみゅーたぶるこれくしょん",
    description: "作成後に変更できないコレクション。スレッドセーフで、変更操作は新しいインスタンスを返す。System.Collections.Immutable名前空間で提供。",
    category: "データ構造",
  },
  // ── OOP ──────────────────────────────────────────────────────────────────
  {
    term: "クラス",
    reading: "くらす",
    description: "オブジェクトの設計図。フィールド・プロパティ・メソッド・イベントをまとめて定義する参照型。classキーワードで宣言する。",
    category: "OOP",
  },
  {
    term: "オブジェクト",
    reading: "おぶじぇくと",
    description: "クラスから生成される実体（インスタンス）。new演算子で作成され、クラスで定義されたメンバーにアクセスできる。",
    category: "OOP",
  },
  {
    term: "プロパティ",
    reading: "ぷろぱてぃ",
    description: "getとsetアクセサーでフィールドの読み書きを制御する仕組み。自動プロパティ（public string Name { get; set; }）で簡潔に書ける。",
    category: "OOP",
  },
  {
    term: "コンストラクタ",
    reading: "こんすとらくた",
    description: "オブジェクト生成時に呼ばれる特殊なメソッド。クラスと同じ名前で戻り値を持たない。初期値の設定に使う。",
    category: "OOP",
  },
  {
    term: "継承",
    reading: "けいしょう",
    description: "既存クラスの機能を引き継いで新しいクラスを作る仕組み。C#は単一継承のみサポートするが、複数のインターフェースを実装できる。",
    category: "OOP",
  },
  {
    term: "インターフェース",
    reading: "いんたーふぇーす",
    description: "メソッドやプロパティの契約を定義する型。interfaceキーワードで宣言し、実装クラスが具体的な処理を提供する。",
    category: "OOP",
  },
  {
    term: "抽象クラス",
    reading: "ちゅうしょうくらす",
    description: "直接インスタンス化できない基底クラス。abstractキーワードで宣言し、抽象メソッドは派生クラスで実装を強制する。",
    category: "OOP",
  },
  {
    term: "ポリモーフィズム",
    reading: "ぽりもーふぃずむ",
    description: "同じインターフェースや基底クラスの参照で異なる派生クラスの動作を呼び出せる仕組み。virtual/overrideで実現する。",
    category: "OOP",
  },
  {
    term: "カプセル化",
    reading: "かぷせるか",
    description: "データとそれを操作するメソッドを一つにまとめ、外部からのアクセスを制限する原則。アクセス修飾子で可視性を制御する。",
    category: "OOP",
  },
  {
    term: "構造体",
    reading: "こうぞうたい",
    description: "値型のユーザー定義型。structキーワードで宣言し、小さなデータのグループ化に適する。継承はできないがインターフェースを実装可能。",
    category: "OOP",
  },
  {
    term: "レコード",
    reading: "れこーど",
    description: "C# 9以降で使えるイミュータブルなデータ型。record宣言で自動的にEquals・GetHashCode・ToStringが生成される。with式によるコピーも可能。",
    category: "OOP",
  },
  {
    term: "列挙型",
    reading: "れっきょがた",
    description: "名前付き定数の集合を定義する型。enumキーワードで宣言し、型安全な定数として使う。Flags属性でビットフラグとしても利用可能。",
    category: "OOP",
  },
  {
    term: "アクセス修飾子",
    reading: "あくせすしゅうしょくし",
    description: "メンバーの可視性を制御するキーワード。public（どこからでも）・private（クラス内のみ）・protected（派生クラスまで）・internal（同一アセンブリ）。",
    category: "OOP",
  },
  {
    term: "sealed",
    reading: "しーるど",
    description: "クラスの継承やメソッドのオーバーライドを禁止するキーワード。パフォーマンス最適化やセキュリティ目的で使用する。",
    category: "OOP",
  },
  {
    term: "ジェネリクス",
    reading: "じぇねりくす",
    description: "型パラメータを使って汎用的なクラス・メソッドを定義する仕組み。List<T>のようにTが具体的な型に置き換わる。型安全性と再利用性を両立する。",
    category: "OOP",
  },
  // ── モダンC# ────────────────────────────────────────────────────────────
  {
    term: "LINQ",
    reading: "りんく",
    description: "Language Integrated Query。C#の構文内でコレクションやデータソースに対するクエリを記述できる統合クエリ言語。Where・Select・OrderByなどのメソッドを提供する。",
    category: "モダンC#",
  },
  {
    term: "ラムダ式",
    reading: "らむだしき",
    description: "=> 演算子を使った無名メソッドの簡潔な記法。(x) => x * 2 のように書き、デリゲートやLINQで多用される。",
    category: "モダンC#",
  },
  {
    term: "デリゲート",
    reading: "でりげーと",
    description: "メソッドへの参照を保持する型。delegateキーワードで宣言し、コールバックやイベントの実装に使用する。",
    category: "モダンC#",
  },
  {
    term: "Action<T>",
    reading: "あくしょん",
    description: "戻り値なしのメソッドを参照する汎用デリゲート。Action・Action<T>・Action<T1,T2>のように0〜16個の引数をサポートする。",
    category: "モダンC#",
  },
  {
    term: "Func<T>",
    reading: "ふぁんく",
    description: "戻り値ありのメソッドを参照する汎用デリゲート。最後の型パラメータが戻り値の型となる。Func<int, string>はintを受け取りstringを返す。",
    category: "モダンC#",
  },
  {
    term: "イベント",
    reading: "いべんと",
    description: "オブジェクトの状態変化を通知する仕組み。eventキーワードで宣言し、+=でハンドラーを登録、-=で解除する。",
    category: "モダンC#",
  },
  {
    term: "async/await",
    reading: "えいしんく・あうぇいと",
    description: "非同期プログラミングのキーワード。asyncでメソッドを非同期に、awaitで非同期操作の完了を待つ。UIスレッドのブロックを防ぐ。",
    category: "モダンC#",
  },
  {
    term: "Task",
    reading: "たすく",
    description: "非同期操作を表すクラス。Task（戻り値なし）とTask<T>（戻り値あり）があり、async/awaitと組み合わせて使う。",
    category: "モダンC#",
  },
  {
    term: "パターンマッチング",
    reading: "ぱたーんまっちんぐ",
    description: "値の型や構造に基づいて分岐する機能。is式・switch式・プロパティパターン・タプルパターン・リストパターンなどがある。",
    category: "モダンC#",
  },
  {
    term: "遅延実行",
    reading: "ちえんじっこう",
    description: "LINQクエリが定義時ではなく実際に列挙されるまで実行されない仕組み。パフォーマンスの最適化に寄与するが、副作用に注意が必要。",
    category: "モダンC#",
  },
  {
    term: "式本体メンバー",
    reading: "しきほんたいめんばー",
    description: "=> を使ってメソッドやプロパティを一行で定義する構文。int Square(int x) => x * x; のように書く。",
    category: "モダンC#",
  },
  {
    term: "null合体演算子",
    reading: "なるがったいえんざんし",
    description: "?? 演算子。左辺がnullの場合に右辺の値を返す。string name = input ?? \"default\"; のように使う。",
    category: "モダンC#",
  },
  {
    term: "null条件演算子",
    reading: "なるじょうけんえんざんし",
    description: "?. 演算子。左辺がnullでない場合のみメンバーにアクセスする。person?.Name のように書き、NullReferenceExceptionを防ぐ。",
    category: "モダンC#",
  },
  {
    term: "非同期ストリーム",
    reading: "ひどうきすとりーむ",
    description: "IAsyncEnumerable<T>による非同期のデータストリーム。await foreachで非同期にデータを逐次処理できる。",
    category: "モダンC#",
  },
  // ── Web ──────────────────────────────────────────────────────────────────
  {
    term: "ASP.NET Core",
    reading: "えーえすぴーどっとねっとこあ",
    description: "クロスプラットフォームのWebフレームワーク。MVC・Razor Pages・Web API・Blazorなど複数のプログラミングモデルをサポートする。",
    category: "Web",
  },
  {
    term: "ミドルウェア",
    reading: "みどるうぇあ",
    description: "HTTPリクエスト/レスポンスパイプラインで処理を行うコンポーネント。認証・ログ・CORS・ルーティングなどがミドルウェアとして実装される。",
    category: "Web",
  },
  {
    term: "依存性注入",
    reading: "いぞんせいちゅうにゅう",
    description: "Dependency Injection（DI）。オブジェクトの依存関係を外部から注入する設計パターン。ASP.NET Coreには組み込みのDIコンテナがある。",
    category: "Web",
  },
  {
    term: "コントローラー",
    reading: "こんとろーらー",
    description: "MVCやWeb APIでHTTPリクエストを処理するクラス。[ApiController]属性で修飾し、アクションメソッドでリクエストに応答する。",
    category: "Web",
  },
  {
    term: "Blazor",
    reading: "ぶれいざー",
    description: "C#でインタラクティブなWebUIを構築するフレームワーク。WebAssembly版（クライアントサイド）とServer版（サーバーサイド）がある。",
    category: "Web",
  },
  {
    term: "Razor",
    reading: "れいざー",
    description: "C#とHTMLを組み合わせるテンプレート構文。@記号でC#コードを埋め込み、Razor Pages・MVC Views・Blazorコンポーネントで使用される。",
    category: "Web",
  },
  {
    term: "Entity Framework Core",
    reading: "えんてぃてぃふれーむわーくこあ",
    description: "オブジェクトリレーショナルマッパー（ORM）。C#オブジェクトとデータベーステーブルをマッピングし、LINQでSQLを生成・実行する。",
    category: "Web",
  },
  {
    term: "DbContext",
    reading: "でぃーびーこんてきすと",
    description: "EF Coreのデータベースセッションを表すクラス。エンティティの追跡・クエリ・保存を管理する中心的なクラス。",
    category: "Web",
  },
  {
    term: "マイグレーション",
    reading: "まいぐれーしょん",
    description: "EF Coreのデータベーススキーマのバージョン管理機能。モデルの変更をマイグレーションファイルとして記録し、データベースに適用する。",
    category: "Web",
  },
  {
    term: "Swagger",
    reading: "すわっがー",
    description: "Web APIの仕様を自動文書化するツール。Swashbuckleパッケージで統合し、対話的なAPI仕様書を自動生成する。",
    category: "Web",
  },
  {
    term: "CORS",
    reading: "こーす",
    description: "Cross-Origin Resource Sharing。異なるオリジンからのHTTPリクエストを許可する仕組み。Web APIで外部フロントエンドからアクセスする際に必要。",
    category: "Web",
  },
  {
    term: "JWT",
    reading: "じぇいだぶりゅーてぃー",
    description: "JSON Web Token。ステートレスな認証トークン。ヘッダー・ペイロード・署名の3部分からなり、Web APIの認証に広く使われる。",
    category: "Web",
  },
  // ── テスト ──────────────────────────────────────────────────────────────
  {
    term: "xUnit",
    reading: "えっくすゆにっと",
    description: ".NETのテストフレームワーク。[Fact]で単一テスト、[Theory]でパラメータ化テストを定義する。",
    category: "テスト",
  },
  {
    term: "アサーション",
    reading: "あさーしょん",
    description: "テストで期待値と実際の値を比較する検証メソッド。Assert.Equal・Assert.True・Assert.Throwsなどがある。",
    category: "テスト",
  },
  {
    term: "モック",
    reading: "もっく",
    description: "テスト用の偽オブジェクト。Moqライブラリなどで依存性の振る舞いをシミュレートし、単体テストの独立性を確保する。",
    category: "テスト",
  },
  {
    term: "AAA パターン",
    reading: "とりぷるえーぱたーん",
    description: "テストの構造化パターン。Arrange（準備）・Act（実行）・Assert（検証）の3段階でテストを記述する。",
    category: "テスト",
  },
  {
    term: "ブレークポイント",
    reading: "ぶれーくぽいんと",
    description: "デバッガで実行を一時停止する地点。条件付きブレークポイントやヒットカウントで柔軟な停止条件を設定できる。",
    category: "テスト",
  },
  {
    term: "BenchmarkDotNet",
    reading: "べんちまーくどっとねっと",
    description: ".NETのパフォーマンス測定ライブラリ。メソッドの実行時間やメモリ割り当てを正確に測定し、レポートを生成する。",
    category: "テスト",
  },
  // ── 応用 ────────────────────────────────────────────────────────────────
  {
    term: "例外",
    reading: "れいがい",
    description: "実行時エラーを表すオブジェクト。try-catch-finallyで捕捉し、throwで送出する。Exceptionクラスを基底とする階層構造を持つ。",
    category: "応用",
  },
  {
    term: "カスタム例外",
    reading: "かすたむれいがい",
    description: "Exceptionクラスを継承して作成する独自の例外。ドメイン固有のエラー情報を保持し、適切なエラーハンドリングを実現する。",
    category: "応用",
  },
  {
    term: "正規表現",
    reading: "せいきひょうげん",
    description: "文字列のパターンマッチングを行う表現方法。System.Text.RegularExpressionsのRegexクラスで利用する。",
    category: "応用",
  },
  {
    term: "シリアライズ",
    reading: "しりあらいず",
    description: "オブジェクトをJSON・XML・バイナリなどの形式に変換すること。System.Text.JsonやNewtonsoftJsonが一般的。",
    category: "応用",
  },
  {
    term: "デシリアライズ",
    reading: "でしりあらいず",
    description: "JSON・XML・バイナリなどの形式からオブジェクトに復元すること。シリアライズの逆操作。",
    category: "応用",
  },
  {
    term: "Stream",
    reading: "すとりーむ",
    description: "バイトの連続したデータの読み書きを抽象化するクラス。FileStream・MemoryStream・NetworkStreamなどの派生クラスがある。",
    category: "応用",
  },
  {
    term: "using文",
    reading: "ゆーじんぐぶん",
    description: "IDisposableオブジェクトのリソース解放を自動化する構文。using宣言（C# 8）で更に簡潔に書ける。",
    category: "応用",
  },
  {
    term: "デザインパターン",
    reading: "でざいんぱたーん",
    description: "ソフトウェア設計でよく使われる問題解決の定石。Singleton・Factory・Observer・Strategyなど、GoFの23パターンが有名。",
    category: "応用",
  },
  {
    term: "Singleton",
    reading: "しんぐるとん",
    description: "クラスのインスタンスを1つだけに制限するデザインパターン。DIコンテナでAddSingleton<T>()として登録するのが現代的な実装方法。",
    category: "応用",
  },
  {
    term: "NuGet",
    reading: "にゅーげっと",
    description: ".NETのパッケージマネージャー。外部ライブラリの追加・更新・削除を管理する。dotnet add packageコマンドで利用する。",
    category: "応用",
  },
  {
    term: "dotnet CLI",
    reading: "どっとねっとしーえるあい",
    description: ".NETのコマンドラインツール。dotnet new・dotnet build・dotnet run・dotnet testなどでプロジェクトの作成・ビルド・実行を行う。",
    category: "応用",
  },
  {
    term: ".csproj",
    reading: "しーしゃーぷぷろじぇ",
    description: "C#プロジェクトファイル。XML形式でターゲットフレームワーク・NuGetパッケージ参照・ビルド設定などを定義する。",
    category: "応用",
  },
  {
    term: "アセンブリ",
    reading: "あせんぶり",
    description: ".NETアプリケーションの配置単位。.dllまたは.exeファイルとして出力され、型やリソースを含む。",
    category: "応用",
  },
  {
    term: "Dapper",
    reading: "だっぱー",
    description: "軽量なORMライブラリ。SQL文を直接記述しながら、結果を自動的にオブジェクトにマッピングする。EF Coreより高速。",
    category: "応用",
  },
  {
    term: "CancellationToken",
    reading: "きゃんせれーしょんとーくん",
    description: "非同期操作のキャンセルを通知する仕組み。CancellationTokenSourceで生成し、トークンを非同期メソッドに渡して中断を制御する。",
    category: "応用",
  },
];
