export interface GlossaryTerm {
  term: string;
  reading?: string;
  description: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  { term: "Dart", description: "Googleが開発したオープンソースのプログラミング言語。型安全・高パフォーマンスを特徴とし、FlutterのメインAURENTいくつの言語として広く使われる。" },
  { term: "Flutter", description: "DartをベースにしたGoogleのUIフレームワーク。iOS・Android・Web・デスクトップのクロスプラットフォームアプリを単一コードベースで開発できる。" },
  { term: "Null Safety", description: "Dart 2.12で導入されたnull安全機能。コンパイル時にnull参照エラーを検出し、NullPointerExceptionを防ぐ。" },
  { term: "Future", description: "非同期処理の結果を表す型。将来完了する値または例外を保持し、then・catchError・async/awaitと組み合わせて使う。" },
  { term: "Stream", description: "非同期イベントのシーケンスを表す型。複数の値を時系列で配信し、listenやawait forで受信する。" },
  { term: "async/await", description: "非同期処理を同期的なコードのように記述するための構文。asyncを付けた関数内でawaitを使い、Futureの完了を待つ。" },
  { term: "Isolate", description: "Dartの並行処理の単位。スレッドとは異なりメモリを共有せず、メッセージパッシングで通信する軽量な実行コンテキスト。" },
  { term: "Mixin", description: "mixinキーワードで定義し、withを使って複数クラスにまたがって機能を追加する仕組み。多重継承の代替として使われる。" },
  { term: "Extension", description: "extensionキーワードを使って既存クラスに新しいメソッドやゲッターを追加する機能。ソースコードを変更せずに型を拡張できる。" },
  { term: "Records", description: "Dart 3で導入された不変な匿名複合値型。複数の値をまとめて扱い、関数から複数の値を返す際などに便利。" },
  { term: "Patterns", description: "Dart 3で強化されたパターンマッチング機能。switch式やif文と組み合わせて値の構造を検査・分解する。" },
  { term: "sealed class", reading: "シールドクラス", description: "sealedキーワードで定義するクラス。同一ライブラリ内でのみサブクラスを定義でき、switch式で網羅的なマッチングが保証される。" },
  { term: "enum", description: "限られた値のセットを定義する列挙型。Dart 2.17以降では、メソッドやインターフェースを持つ拡張enumが使える。" },
  { term: "factory", description: "factoryキーワードで定義するコンストラクタ。新しいインスタンスの代わりに既存インスタンスを返したり、型の変換ロジックをカプセル化できる。" },
  { term: "const", description: "コンパイル時に値が確定する定数を宣言するキーワード。constオブジェクトはコンパイル時定数であり、再利用される。" },
  { term: "final", description: "一度代入すると変更できない変数を宣言するキーワード。constと異なりランタイム時の値でもよい。" },
  { term: "late", description: "non-nullable変数を宣言時に初期化せず、後で初期化することを明示するキーワード。遅延初期化を可能にする。" },
  { term: "var", description: "型推論を使って変数を宣言するキーワード。代入された値の型が推論され、その後の型は固定される。" },
  { term: "dynamic", description: "実行時まで型が決まらないことを示す型アノテーション。型チェックをバイパスするため、使用には注意が必要。" },
  { term: "Object", description: "Dartのすべての非null型の基底クラス。Object?はnullも含む全型のスーパータイプ。" },
  { term: "Widget", description: "FlutterにおけるUIの基本構成要素。すべてのUI要素はウィジェットとして表現され、ウィジェットツリーを構成する。" },
  { term: "StatelessWidget", description: "状態を持たないFlutterウィジェット。外部から渡されるデータのみに依存してUIを構築するbuildメソッドを実装する。" },
  { term: "StatefulWidget", description: "変化する状態を持つFlutterウィジェット。StateクラスとsetStateを使って状態の変化をUIに反映する。" },
  { term: "BuildContext", description: "ウィジェットツリー内でのウィジェットの位置を表すオブジェクト。Themeやスクリーンサイズなどのデータにアクセスする際に使用する。" },
  { term: "pubspec.yaml", description: "Dartプロジェクトのメタデータと依存パッケージを定義するYAMLファイル。プロジェクト名・バージョン・依存関係を記述する。" },
  { term: "pub.dev", description: "Dartの公式パッケージリポジトリ。Dartおよびflutterパッケージを検索・閲覧・公開できるウェブサービス。" },
  { term: "Dart SDK", description: "Dartの標準開発キット。dartコマンド・コア言語ライブラリ・開発ツール一式が含まれる。" },
  { term: "DartPad", description: "ブラウザ上でDartとFlutterのコードを試せる公式オンラインエディタ。インストール不要で素早く動作確認ができる。" },
  { term: "Hot Reload", description: "Flutterの開発機能。コードの変更をアプリの状態を保ったまま即座に反映でき、開発イテレーションを大幅に短縮する。" },
  { term: "Scaffold", description: "Flutterのマテリアルデザインの基本レイアウト構造を提供するウィジェット。AppBar・body・floatingActionButtonなどを含む。" },
  { term: "MaterialApp", description: "マテリアルデザインのアプリ全体を設定するFlutterウィジェット。テーマ・ルーティング・ロケールなどをアプリレベルで定義する。" },
  { term: "StreamController", description: "Streamを手動で作成・管理するクラス。sinkを使ってイベントを追加し、streamプロパティで外部に公開する。" },
  { term: "Completer", description: "Futureを手動で完了させるためのクラス。completer.futureを返し、completer.completeで値を設定する。" },
  { term: "typedef", description: "型に別名を付けるためのキーワード。特に関数型に名前を付けてコードの可読性を高めるために使う。" },
  { term: "RegExp", description: "正規表現パターンを表すDartのクラス。文字列のマッチング・抽出・置換に使用する。" },
  { term: "StringBuffer", description: "文字列を効率的に結合するためのクラス。+演算子による文字列結合の繰り返しより高パフォーマンス。" },
  { term: "Iterable", description: "順次アクセス可能な要素のコレクションを表す抽象クラス。List・Set・MapのValuesなどがIterableを実装する。" },
  { term: "List", description: "順序付き要素のコレクション。インデックスで要素にアクセスでき、可変長（grow可能）と固定長の両方がある。" },
  { term: "Map", description: "キーと値のペアを格納するコレクション。キーは一意であり、対応する値へ高速にアクセスできる。" },
  { term: "Set", description: "重複を許さない要素のコレクション。要素の存在確認がO(1)で行えるHashSetなどの実装がある。" },
  { term: "abstract class", reading: "抽象クラス", description: "abstractキーワードで定義するクラス。直接インスタンス化できず、サブクラスが実装すべき抽象メソッドを持つ。" },
  { term: "implements", description: "クラスがインターフェース（別クラスの公開API）を実装することを宣言するキーワード。すべてのメンバーを実装する必要がある。" },
  { term: "extends", description: "クラスが別クラスを継承することを宣言するキーワード。単一継承のみ可能で、親クラスのメンバーを引き継ぐ。" },
  { term: "with", description: "mixinをクラスに適用するキーワード。複数のmixinをカンマ区切りで指定でき、コードを再利用する。" },
  { term: "generics", reading: "ジェネリクス", description: "型パラメータを使ってクラス・関数・インターフェースを汎用化する仕組み。型安全なコレクション操作などに使われる。" },
  { term: "cascade notation", reading: "カスケード記法", description: "..演算子を使って同一オブジェクトに連続してメソッド呼び出しやプロパティ設定を行う記法。" },
  { term: "spread operator", reading: "スプレッド演算子", description: "...と...?を使ってコレクションの要素を別のコレクションリテラル内に展開する演算子。" },
  { term: "named constructor", reading: "名前付きコンストラクタ", description: "クラス名.名前の形式で定義する追加コンストラクタ。複数の初期化方法を持つクラスを作るために使う。" },
  { term: "initializing formal", description: "this.フィールド名の形式でコンストラクタのパラメータを直接フィールドに代入する省略記法。" },
  { term: "assert", description: "開発モードでのみ実行される条件チェック。条件が偽の場合AssertionErrorを投げる。本番ビルドでは無視される。" },
  { term: "dart:core", description: "Dartの基本的なクラスと関数を提供する標準ライブラリ。自動的にインポートされ、int・String・Listなどが含まれる。" },
  { term: "dart:async", description: "非同期プログラミングのサポートを提供する標準ライブラリ。Future・Stream・StreamControllerなどが含まれる。" },
  { term: "dart:io", description: "ファイルI/O・ネットワーク・プロセス管理などを提供する標準ライブラリ。FlutterのWebでは使用不可。" },
  { term: "dart:convert", description: "JSON・UTF-8・Base64などのエンコード・デコードを提供する標準ライブラリ。jsonEncodeとjsonDecodeが主要な関数。" },
  { term: "dart:math", description: "数学関数・定数（pi・eなど）・乱数生成を提供する標準ライブラリ。" },
  { term: "dart:developer", description: "開発・デバッグ用のユーティリティを提供する標準ライブラリ。log関数やタイムラインAPIが含まれる。" },
  { term: "pubspec.lock", description: "実際に使用されている依存パッケージの正確なバージョンを記録したファイル。再現可能なビルドを保証する。" },
  { term: "pub get", description: "pubspec.yamlに記載された依存パッケージをダウンロードして解決するコマンド。dart pub getで実行する。" },
  { term: "dart analyze", description: "Dartコードの静的解析を実行するコマンド。型エラー・非推奨API使用・スタイル違反などを検出する。" },
  { term: "dart format", description: "Dartコードを公式のスタイルガイドに沿って自動整形するコマンド。チーム内のコードスタイルを統一する。" },
  { term: "dart fix", description: "静的解析で検出された問題を自動修正するコマンド。非推奨APIの置き換えなどを一括で適用できる。" },
  { term: "dart compile", description: "DartコードをネイティブバイナリやJavaScriptにコンパイルするコマンド群。dart compile exeでスタンドアロン実行ファイルを生成する。" },
  { term: "FVM", description: "Flutter Version Manager。複数バージョンのFlutter/Dartを管理し、プロジェクトごとにバージョンを切り替えるツール。" },
  { term: "Shelf", description: "Dartのサーバーサイドウェブフレームワーク。ミドルウェアパイプライン・ルーティング・HTTPハンドラを提供する。" },
  { term: "mockito", description: "Dartのモックライブラリ。テスト時に依存クラスのモックを自動生成し、振る舞いを制御するためのパッケージ。" },
  { term: "test package", reading: "testパッケージ", description: "Dartの標準テストフレームワーク。test・group・expect関数を提供し、ユニットテストと統合テストを記述する。" },
  { term: "coverage", reading: "カバレッジ", description: "テストがコードのどの割合を実行しているかを示す指標。dart testの--coverageオプションで計測できる。" },
  { term: "Hot Restart", description: "FlutterアプリをDartVMの状態をリセットして再起動する機能。Hot Reloadで反映できない変更（main関数変更など）に使う。" },
  { term: "Tree Shaking", description: "使用されていないコードをビルド時に自動的に除去する最適化技術。Dartのコンパイラが自動的に行い、バンドルサイズを削減する。" },
  { term: "AOT compilation", reading: "AOTコンパイル", description: "Ahead-Of-Timeコンパイル。実行前にネイティブコードにコンパイルし、起動速度と実行パフォーマンスを向上させる。" },
  { term: "JIT compilation", reading: "JITコンパイル", description: "Just-In-Timeコンパイル。実行時にコードをコンパイルする方式。開発時のHot ReloadはJITを活用している。" },
  { term: "class modifiers", reading: "クラスモディファイア", description: "Dart 3で導入されたbase・interface・final・sealed・mixinなどのキーワード。クラスの継承・実装可能性を細かく制御する。" },
  { term: "record type", reading: "レコード型", description: "Dart 3で導入された匿名複合値型。(int, String)や(x: 1, y: 2)の形式で複数の値を一つにまとめられる。" },
  { term: "pattern matching", reading: "パターンマッチング", description: "値の構造を検査してマッチした場合に変数へ分解代入するDart 3の機能。switch式・if-caseなどで使用する。" },
  { term: "destructuring", reading: "分解代入", description: "パターンマッチングを使ってリスト・マップ・レコード・オブジェクトの要素を個別の変数に取り出す操作。" },
  { term: "guard clause", reading: "ガード節", description: "パターンマッチングのcaseにwhenキーワードで追加する条件式。パターンが一致してもwhenが偽なら次のcaseへ進む。" },
  { term: "cascade", description: "..演算子を使って同一オブジェクトへの複数の操作を連鎖させる記法。setterの呼び出しや操作のチェーンに便利。" },
  { term: "sound null safety", description: "Dartのnull安全システムが型システム全体で整合性を保証すること。soundな状態ではnull参照エラーがコンパイル時に完全に検出される。" },
  { term: "late final", description: "一度だけ代入可能な遅延初期化フィールド。読み込み前に必ず代入され、二度以上の代入はエラーになる。" },
];
