export interface GlossaryTerm {
  term: string;
  reading?: string;
  description: string;
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  { term: "PHP", description: "PHP: Hypertext Preprocessor の略。サーバーサイドで動作するスクリプト言語。" },
  { term: "変数", reading: "へんすう", description: "データを格納するための名前付きの入れ物。PHPでは$記号で始まる。" },
  { term: "定数", reading: "ていすう", description: "一度定義すると値を変更できない識別子。defineまたはconstで定義する。" },
  { term: "配列", reading: "はいれつ", description: "複数の値を順序付けて格納するデータ構造。インデックス配列と連想配列がある。" },
  { term: "連想配列", reading: "れんそうはいれつ", description: "文字列キーと値のペアで構成される配列。他言語のハッシュマップに相当。" },
  { term: "関数", reading: "かんすう", description: "再利用可能なコードブロック。functionキーワードで定義する。" },
  { term: "クロージャ", description: "外側のスコープの変数を参照できる無名関数。useキーワードで変数を取り込む。" },
  { term: "アロー関数", description: "fn() => 構文で定義する簡潔な無名関数。外側の変数を自動的にキャプチャする。" },
  { term: "クラス", description: "オブジェクトの設計図。プロパティとメソッドを定義する。" },
  { term: "オブジェクト", description: "クラスから生成されたインスタンス。new演算子で作成する。" },
  { term: "インターフェース", description: "クラスが実装すべきメソッドの契約を定義する型。interfaceキーワードで宣言。" },
  { term: "トレイト", description: "クラス間でメソッドを共有するための仕組み。多重継承の代替として使用。" },
  { term: "名前空間", reading: "なまえくうかん", description: "クラスや関数の名前衝突を避けるための仕組み。namespaceキーワードで定義。" },
  { term: "Composer", description: "PHPの依存関係管理ツール。パッケージのインストールとオートロードを提供。" },
  { term: "PDO", description: "PHP Data Objects。データベースにアクセスするための統一インターフェース。" },
  { term: "プリペアドステートメント", description: "SQL文を事前に準備し、パラメータを安全にバインドする仕組み。SQLインジェクション対策。" },
  { term: "セッション", description: "ユーザーの状態をサーバー側で管理する仕組み。session_startで開始。" },
  { term: "クッキー", description: "ブラウザ側に保存される小さなデータ。setcookie関数で設定。" },
  { term: "スーパーグローバル", description: "全スコープから参照可能な組み込み変数。$_GET、$_POST、$_SESSIONなど。" },
  { term: "例外", reading: "れいがい", description: "プログラム実行中のエラーを表すオブジェクト。try-catchで処理する。" },
  { term: "enum", description: "列挙型。PHP 8.1で追加。限られた値のセットを定義する。" },
  { term: "match式", description: "switchの改良版。厳密比較を行い、値を返す式。PHP 8.0で追加。" },
  { term: "Nullable型", description: "型宣言の前に?を付けることでnullも許容する型。例: ?string" },
  { term: "Union型", description: "複数の型のいずれかを受け付ける型宣言。例: int|string" },
  { term: "readonly", description: "一度設定すると変更できないプロパティ。PHP 8.1で追加。" },
  { term: "Attribute", description: "PHP 8で追加されたメタデータ付与の仕組み。#[...]構文で記述。" },
  { term: "Fiber", description: "PHP 8.1で追加された軽量な並行処理の仕組み。中断・再開が可能。" },
  { term: "ジェネレータ", description: "yieldキーワードを使ってイテレータを簡単に作成する関数。" },
  { term: "PHPUnit", description: "PHPの標準的なユニットテストフレームワーク。" },
  { term: "PSR", description: "PHP Standards Recommendations。PHP-FIGが策定する標準規約。" },
  { term: "PSR-4", description: "オートロードの標準規約。名前空間とディレクトリ構造を対応付ける。" },
  { term: "Xdebug", description: "PHPのデバッグ・プロファイリング用拡張モジュール。" },
  { term: "CSRF", description: "Cross-Site Request Forgery。ユーザーの意図しないリクエストを送信させる攻撃。" },
  { term: "XSS", description: "Cross-Site Scripting。悪意のあるスクリプトを注入する攻撃。htmlspecialcharsで対策。" },
  { term: "SQLインジェクション", description: "SQL文に不正な入力を挿入する攻撃。プリペアドステートメントで防止。" },
  { term: "Laravel", description: "PHPの人気フルスタックWebフレームワーク。Eloquent ORM、Bladeテンプレートを含む。" },
  { term: "Symfony", description: "PHPの堅牢なWebフレームワーク。再利用可能なコンポーネント群で構成。" },
  { term: "MVC", description: "Model-View-Controller。アプリケーションを3つの層に分離するアーキテクチャパターン。" },
  { term: "REST API", description: "Representational State Transfer。HTTPメソッドを使ったWeb APIの設計スタイル。" },
  { term: "JSON", description: "JavaScript Object Notation。データ交換用の軽量フォーマット。json_encode/json_decodeで処理。" },
  { term: "HEREDOC", description: "<<<演算子を使った複数行文字列リテラル。変数展開が可能。" },
  { term: "NOWDOC", description: "シングルクォート版のHEREDOC。変数展開を行わない。" },
  { term: "strict_types", description: "declare(strict_types=1)で有効化。型の暗黙変換を禁止し厳密チェックを行う。" },
  { term: "名前付き引数", reading: "なまえつきひきすう", description: "引数名を指定して関数を呼び出す機能。順序を自由に変更可能。PHP 8.0で追加。" },
  { term: "コンストラクタプロモーション", description: "コンストラクタの引数でプロパティ宣言を同時に行う機能。PHP 8.0で追加。" },
  { term: "Null合体演算子", description: "?? 演算子。左辺がnullの場合に右辺の値を返す。" },
  { term: "スプレッド演算子", description: "... 演算子。配列の展開や可変長引数に使用する。" },
  { term: "型キャスト", reading: "かたきゃすと", description: "(int)、(string)などのキャスト演算子による明示的な型変換。" },
  { term: "マジックメソッド", description: "__で始まる特殊なメソッド。__construct、__toString、__getなど。" },
  { term: "デストラクタ", description: "__destructメソッド。オブジェクト破棄時に自動的に呼ばれる。" },
  { term: "抽象クラス", reading: "ちゅうしょうくらす", description: "abstractキーワードで定義。直接インスタンス化できず、継承して使用する。" },
  { term: "オートロード", description: "クラスが必要になった時に自動的にファイルを読み込む仕組み。" },
  { term: "Packagist", description: "Composerのメインパッケージリポジトリ。PHPライブラリを検索・インストールできる。" },
  { term: "SPL", description: "Standard PHP Library。PHPに組み込まれた標準データ構造とイテレータのコレクション。" },
  { term: "正規表現", reading: "せいきひょうげん", description: "文字列のパターンマッチングに使う記法。preg_match等のPCRE関数で使用。" },
  { term: "依存性注入", reading: "いぞんせいちゅうにゅう", description: "オブジェクトの依存関係を外部から渡すデザインパターン。テスト容易性を向上。" },
  { term: "ミドルウェア", description: "リクエスト処理の前後に挟む処理層。認証やログなど横断的な関心事を扱う。" },
  { term: "テンプレートエンジン", description: "HTMLとロジックを分離するための仕組み。Blade、Twigなどがある。" },
  { term: "PHP-FIG", description: "PHP Framework Interop Group。フレームワーク間の相互運用性を推進する団体。" },
  { term: "Intersection型", description: "複数の型を同時に満たすことを要求する型宣言。A&B構文。PHP 8.1で追加。" },
  { term: "static変数", description: "関数内でstatic宣言された変数。関数呼び出し間で値が保持される。" },
  { term: "トランザクション", description: "データベース操作をまとめて成功か失敗を保証する仕組み。ACID特性を持つ。" },
  { term: "password_hash", description: "パスワードを安全にハッシュ化するPHP組み込み関数。bcryptを使用。" },
  { term: "filter_input", description: "外部入力をフィルタリング・検証するための関数。" },
  { term: "array_map", description: "配列の各要素にコールバック関数を適用し、新しい配列を返す関数。" },
  { term: "array_filter", description: "コールバック関数で条件に一致する要素だけを残す関数。" },
  { term: "array_reduce", description: "配列を一つの値に集約するための関数。" },
  { term: "yield", description: "ジェネレータ関数内で値を生成するキーワード。遅延評価を実現する。" },
  { term: "SplStack", description: "SPLが提供するスタック（LIFO）データ構造。" },
  { term: "SplQueue", description: "SPLが提供するキュー（FIFO）データ構造。" },
  { term: "Backed Enum", description: "スカラー値（string|int）を持つ列挙型。データベース格納やシリアライズに便利。" },
  { term: "DateTimeImmutable", description: "変更操作で新しいオブジェクトを返す不変な日時クラス。" },
  { term: "DateInterval", description: "期間を表すクラス。日付の加算・減算に使用する。" },
  { term: "PHPDoc", description: "/** */で記述するドキュメンテーションコメント。@param、@returnなどのタグを使用。" },
  { term: "デザインパターン", description: "ソフトウェア設計で繰り返し使われる問題解決の定石。GoFの23パターンが有名。" },
  { term: "シングルトン", description: "インスタンスを1つだけに制限するデザインパターン。" },
  { term: "ファクトリー", description: "オブジェクト生成をカプセル化するデザインパターン。" },
].sort((a, b) => a.term.localeCompare(b.term, "ja"));
